# Denoising Method Comparison — POC_DDM

Compares **three** denoising methods on raw kinetic (LAMP/DDM) curves, each applied with
its current chosen hyperparameter (no HP sweep re-run in this notebook):

| # | Method | Hyperparameter |
|---|---|---|
| 1 | Moving avg (`ori_curves_avg`) | `config.WINDOW_SIZE_ORI` |
| 2 | Wavelet (universal threshold) | `WAVELETS[0]` = `'sym8'`, `LEVEL`, `THRESH_MODE` |
| 3 | Savitzky-Golay | `SG_POLYORDER`, `SG_OPTIMAL_W` (fixed below) |

In [1]:
import os, sys
import numpy as np
import matplotlib.pyplot as plt
import joblib
import pywt
from scipy.signal import savgol_filter
from scipy.ndimage import uniform_filter1d

sys.path.insert(0, '/vol/bitbucket/gk225/POC_DDM/gk_code')
sys.path.insert(0, '/vol/bitbucket/gk225/POC_DDM/gk_code/main')
import config

try:
    from tqdm import tqdm
except ImportError:
    tqdm = None

print(f'pywt {pywt.__version__} | base: {config.BASE_FOLDER}')

[*] SUCCESS: TensorFlow is utilizing the GPU -> /physical_device:GPU:0

pywt 1.8.0 | base: /vol/bitbucket/gk225/POC_DDM_datasets

In [2]:
# ── Configuration ─────────────────────────────────────────────
# DATASET      = 'POC_DDM_final_nc_subtract'   # or 'POC_DDM_multi'
DATASET      = 'POC_DDM_final'
EXP_FOLDER   = os.path.join(config.BASE_FOLDER, DATASET)
CURVE_TYPE   = 'ori_curves'
WAVELETS     = ['sym8']          # first entry used in comparison
LEVEL        = None
THRESH_MODE  = 'soft'
SG_POLYORDER = 2                 # 2 = quadratic, 3 = cubic
SG_OPTIMAL_W = 69                # current chosen window -- derivative-test sweep on
                                  # D20260807_E00_C00_F4500KHz_U_DDM_02_07

In [3]:
# ── Wavelet ────────────────────────────────────────────────────────────────
def denoise_curve(curve, wavelet, level=LEVEL, mode=THRESH_MODE):
    coeffs     = pywt.wavedec(curve, wavelet, level=level)
    sigma      = np.median(np.abs(coeffs[-1])) / 0.6745
    threshold  = sigma * np.sqrt(2 * np.log(len(curve)))
    new_coeffs = [coeffs[0]] + [pywt.threshold(d, threshold, mode=mode) for d in coeffs[1:]]
    return pywt.waverec(new_coeffs, wavelet)[:len(curve)]

def denoise_all(curves, wavelet):
    it = tqdm(curves, desc=f'Denoising [{wavelet}]', unit='curve') if tqdm else curves
    return np.array([denoise_curve(c, wavelet) for c in it])

# ── SG ─────────────────────────────────────────────────────────────────────────────
def _ensure_odd(w): return w + (1 - w % 2)

def apply_sg(curves, window_length, polyorder):
    w = _ensure_odd(int(window_length)); w = max(w, polyorder + 2)
    return savgol_filter(curves, window_length=w, polyorder=polyorder, axis=1)

# ── Derivative-test sweep -- drives the SG/Wavelet HP search below ─────────────────
def _derivative_scores(curves, param_values, denoise_fn, sample_size=400, seed=0):
    rng    = np.random.default_rng(seed)
    sample = curves[rng.choice(len(curves), size=min(sample_size, len(curves)), replace=False)]
    _ref_w = max(5, _ensure_odd(int(sample.shape[1] * 0.03)))
    ref    = savgol_filter(sample, window_length=_ref_w, polyorder=2, axis=1)
    peak_r = np.abs(np.diff(ref, axis=1)).max(axis=1)
    ro_raw = np.std(np.diff(np.diff(sample, axis=1), axis=1), axis=1)
    prs, ros = [], []
    for p in param_values:
        df = np.diff(denoise_fn(sample, p), axis=1)
        prs.append(np.mean(np.abs(df).max(axis=1) / np.where(peak_r > 0, peak_r, 1)))
        ros.append(np.mean(np.std(np.diff(df, axis=1), axis=1) / np.where(ro_raw > 0, ro_raw, 1)))
    return np.array(prs), np.array(ros)

def _sweet_spot(param_values, roughnesses):
    """First (smallest) param where roughness drops within 2x of its floor (10th pctile)."""
    floor = np.percentile(roughnesses, 10)
    sweet = np.where(roughnesses <= 2.0 * floor)[0]
    return float(param_values[sweet[0]] if len(sweet) else param_values[np.argmin(roughnesses)])

# ── Data loading ────────────────────────────────────────────────────────────────
def list_folders(exp_folder):
    out = []
    for name in sorted(os.listdir(exp_folder)):
        p = os.path.join(exp_folder, name)
        if (os.path.isdir(p) and name not in config.EXCLUDED_FOLDERS
                and os.path.exists(os.path.join(p, config.TRAINING_DATA_PATH))):
            out.append((name, p))
    return out

def load_exp(folder_path):
    d           = joblib.load(os.path.join(folder_path, config.TRAINING_DATA_PATH))
    curves      = np.array(d['curves'][CURVE_TYPE])
    if 'ori_curves_avg' in d['curves']:
        curves_avg = np.array(d['curves']['ori_curves_avg'])
    else:
        curves_avg = uniform_filter1d(np.array(d['curves']['ori_curves']), size=config.WINDOW_SIZE_ORI, axis=1, mode='nearest')
    well_labels = np.array(d['well_labels'])
    return curves, curves_avg, well_labels

print('All functions loaded.')

All functions loaded.

In [4]:
import re
import pandas as pd
from scipy.stats import pearsonr

# ── Colours & display constants ───────────────────────────────────────────────
METHOD_COLORS  = ['#CC79A7', '#E69F00', '#0072B2']
SG_POLY_COLORS = {2: '#0072B2', 3: '#009E73', 4: '#D55E00'}
_M_COLOR       = {'raw': '#999999', 'smoothed': '#CC79A7', 'sg': '#0072B2'}
_WAVELET_COLORS_CYCLE = ['#E69F00', '#56B4E9', '#009E73', '#F0E442', '#882255']

# HP search candidates (feed the SG/Wavelet HP search cells below)
SG_POLYORDERS      = [2, 3, 4]
WAVELET_CANDIDATES = [
    # 'db4', 'db6', 'db8',
    'sym4', 'sym6', 'sym8',
    # 'coif2', 'coif4',
    # 'bior3.5', 'bior4.4',
]

# ── Shared helpers ────────────────────────────────────────────────────────────
def _safe_corr(a, b):
    """Pearson r; returns np.nan if either input is constant."""
    return np.nan if np.std(a) == 0 or np.std(b) == 0 else pearsonr(a, b)[0]


def _full_metrics(raw, denoised):
    """Mean per-sample SNR, noise%, TV ratio, Pearson fidelity."""
    noise  = raw - denoised
    ns     = np.std(noise, axis=1)
    sr     = raw.max(axis=1) - raw.min(axis=1)
    vd, vn = np.var(denoised, axis=1), np.var(noise, axis=1)
    tv_d   = np.abs(np.diff(denoised, axis=1)).sum(axis=1)
    tv_r   = np.abs(np.diff(raw,      axis=1)).sum(axis=1)
    with np.errstate(divide='ignore', invalid='ignore'):
        snr_v   = np.where(vn > 0, 10*np.log10(np.where(vn > 0, vd/vn, 1.0)), np.nan)
        noise_v = np.where(sr > 0, ns / np.where(sr > 0, sr, 1.0) * 100, np.nan)
        tv_v    = tv_d / np.where(tv_r > 0, tv_r, np.nan)
    return {
        'snr':    float(np.nanmean(snr_v)),
        'noise%': float(np.nanmean(noise_v)),
        'tv':     float(np.nanmean(tv_v)),
        'corr':   float(np.nanmean([_safe_corr(raw[i], denoised[i]) for i in range(len(raw))])),
    }


# ── Method resolver ───────────────────────────────────────────────────────────
def _resolve_methods(r, methods):
    """Return [(array, title, color), ...] for the requested method keys.

    Keys:
      'smoothed'       moving average
      'sg'             SG (baseline polyorder + fixed window, see config)
      'sg_p2/3/4'      SG HP search result (per-polyorder auto window)
      'wv_<name>'      wavelet HP candidate  e.g. 'wv_sym6'
      '<name>'         baseline wavelet from WAVELETS  e.g. 'sym8'
    """
    wv_iter = iter(_WAVELET_COLORS_CYCLE)
    out = []
    for key in methods:
        if key == 'raw':
            out.append((r['raw'], 'Raw', _M_COLOR['raw']))
        elif key == 'smoothed':
            out.append((r['smoothed'],
                        f'Smoothed\n(w={config.WINDOW_SIZE_ORI})', _M_COLOR['smoothed']))
        elif key == 'sg':
            out.append((r.get('sg'),
                        f'SG p={SG_POLYORDER}\n(w={SG_OPTIMAL_W})', _M_COLOR['sg']))
        elif key.startswith('sg_p') and key[4:].isdigit():
            entry = r.get(key)
            if entry is not None:
                poly = int(key[4:])
                out.append((entry['denoised'],
                             f'SG p={poly}\n(w={entry["optimal_w"]})',
                             SG_POLY_COLORS.get(poly, '#888888')))
            else:
                print(f'[!] {key!r} not found — run SG HP search first')
        elif key.startswith('wv_'):
            wv_name = key[3:]
            entry   = r.get(key)
            if entry is not None:
                out.append((entry['denoised'],
                             f'Wavelet\n({wv_name})', next(wv_iter, '#888888')))
            elif wv_name in r.get('denoised', {}):
                out.append((r['denoised'][wv_name],
                             f'Wavelet\n({wv_name})', next(wv_iter, '#888888')))
            else:
                print(f'[!] {key!r} not found — run wavelet HP search first')
        elif key in r.get('denoised', {}):
            out.append((r['denoised'][key],
                        f'Wavelet\n({key})', next(wv_iter, '#888888')))
        else:
            print(f'[!] Unknown method key: {key!r}  (skipped)')
    return [(arr, lbl, col) for arr, lbl, col in out if arr is not None]


def _labels():
    return [
        f'Moving avg\n(w={config.WINDOW_SIZE_ORI})',
        f'Wavelet\n({WAVELETS[0]})',
        f'SG p={SG_POLYORDER}\n(w={SG_OPTIMAL_W})',
    ]

def _ready(r): return 'sg' in r


# ── Quantitative comparison ───────────────────────────────────────────────────
def compare_all_methods(folder_name, methods=None, plot=True):
    """
    Compute 7 denoising metrics and (optionally) plot bar charts.

    methods = None  → 3 baseline methods (smoothed, wavelet, sg), current hyperparams.
    methods = list  → any combination via _resolve_methods keys.

    Metrics: SNR, Noise%, Fidelity, AC lag-1, TV ratio, ΔTTP, SD_max ratio.
    """
    r = results[folder_name]
    if not _ready(r): print(f'[!] Run apply cell first for {folder_name}'); return
    raw = r['raw']

    if methods is None:
        labels  = _labels()
        arrays  = [r['smoothed'], r['denoised'][WAVELETS[0]], r['sg']]
        colors  = METHOD_COLORS
    else:
        resolved = _resolve_methods(r, methods)
        labels   = [l for _, l, _ in resolved]
        arrays   = [a for a, _, _ in resolved]
        colors   = [c for _, _, c in resolved]

    def tv(a): return np.abs(np.diff(a, axis=1)).sum(axis=1)
    def ac1(rw, dn):
        res = rw - dn
        return np.nanmean([np.corrcoef((e := res[i]-res[i].mean())[:-1], e[1:])[0, 1]
                           for i in range(len(res)) if res[i].std() > 0])

    mnames = ['SNR (dB)', 'Noise %', 'Fidelity\n(corr)', 'Residual\nAC lag-1',
              'TV ratio', 'Δ TTP', 'SD_max\nratio']
    better = ['↑', '↓', '↑', '↓', '↓', '↓', '→1']

    def best_idx(row, b):
        fin = np.isfinite(row)
        if not fin.any(): return None
        r_ = np.where(fin, row, np.nan)
        if b == '↓': return int(np.nanargmin(r_))
        if b == '↑': return int(np.nanargmax(r_))
        return int(np.nanargmin(np.abs(r_ - 1.0)))

    n_m  = len(labels)
    sc   = np.full((7, n_m), np.nan)
    _ref_w = max(5, _ensure_odd(int(raw.shape[1] * 0.03)))
    _ref   = savgol_filter(raw, window_length=_ref_w, polyorder=2, axis=1)
    draw   = np.abs(np.diff(_ref, axis=1)); ttp_raw = np.argmax(draw, axis=1).astype(float)
    for mi, den in enumerate(arrays):
        noise  = raw - den; ns = np.std(noise, axis=1); sr = raw.max(axis=1) - raw.min(axis=1)
        vd, vn = np.var(den, axis=1), np.var(noise, axis=1)
        dden   = np.abs(np.diff(den, axis=1))
        with np.errstate(divide='ignore', invalid='ignore'):
            sc[0,mi] = np.nanmean(np.where(vn > 0, 10*np.log10(np.where(vn > 0, vd/vn, 1.0)), np.nan))
            sc[1,mi] = np.nanmean(np.where(sr > 0, ns / np.where(sr > 0, sr, 1.0) * 100, np.nan))
        sc[2,mi] = np.nanmean([_safe_corr(raw[i], den[i]) for i in range(len(raw))])
        sc[3,mi] = ac1(raw, den)
        sc[4,mi] = np.nanmean(tv(den) / np.where(tv(raw) > 0, tv(raw), np.nan))
        sc[5,mi] = np.mean(np.abs(ttp_raw - np.argmax(dden, axis=1).astype(float)))
        sc[6,mi] = np.nanmean(dden.max(axis=1) / np.where(draw.max(axis=1)>0, draw.max(axis=1), np.nan))

    all_mn, all_sc, all_bt = mnames, list(sc), better

    if plot:
        fig, axes_pl = plt.subplots(1, len(all_mn), figsize=(max(6, 1.8*n_m), 5))
        if len(all_mn) == 1: axes_pl = [axes_pl]
        fig.suptitle(f'Quantitative Comparison — {folder_name}', fontsize=11, fontweight='bold')
        x = np.arange(n_m)
        for ax, metric, vals, b in zip(axes_pl, all_mn, all_sc, all_bt):
            best = best_idx(vals, b)
            for xi, (val, color) in enumerate(zip(vals, colors)):
                if np.isnan(val):
                    ax.bar(xi, 1, color='none', edgecolor=color, lw=1.5, ls='--', zorder=3)
                    ax.text(xi, 0.5, 'N/A', ha='center', va='center', fontsize=8, color=color, fontweight='bold')
                else:
                    bar = ax.bar(xi, val, color=color, edgecolor='black', zorder=3)
                    if xi == best: bar[0].set_edgecolor('red'); bar[0].set_linewidth(2.5)
                    ax.text(xi, val, f'{val:.3f}', ha='center', va='bottom', fontsize=7.5)
            ax.set_title(metric, fontweight='bold', fontsize=9)
            ax.set_xticks(x)
            ax.set_xticklabels([l.replace('\n',' ') for l in labels], rotation=30, ha='right', fontsize=8)
            ax.grid(axis='y', alpha=0.3, zorder=0)
        axes_pl[0].set_ylabel('↑ higher = better', fontsize=8, color='gray')
        if len(axes_pl) > 3: axes_pl[3].set_ylabel('↓ lower = better', fontsize=8, color='gray')
        if len(axes_pl) > 6: axes_pl[6].set_ylabel('→ 1.0 = best',     fontsize=8, color='gray')
        note = '■ red outline = best  |  N/A = zero noise variance'
        fig.text(0.99, 0.01, note, ha='right', fontsize=7.5, color='red', style='italic')
        fig.tight_layout(); plt.show(); plt.close(fig)

    # Build DataFrame (methods as rows, metrics as columns)
    directions = {mn.replace('\n', ' '): bt for mn, bt in zip(all_mn, all_bt)}
    df = pd.DataFrame(
        {mn.replace('\n', ' '): [float(v) for v in vals]
         for mn, vals in zip(all_mn, all_sc)},
        index=[l.replace('\n', ' ') for l in labels],
    )

    def _style_col(col):
        d      = directions.get(col.name, '↑')
        finite = col.dropna()
        if finite.empty:
            return [''] * len(col)
        best_lbl = ((finite - 1.0).abs().idxmin() if d == '→1'
                    else finite.idxmin()           if d == '↓'
                    else finite.idxmax())
        return ['background-color: #c8f7c5; font-weight: bold'
                if i == best_lbl else '' for i in col.index]

    try:
        from IPython.display import display
        display(df.style.apply(_style_col).format('{:.4f}', na_rep='N/A')
                  .set_caption(folder_name))
    except Exception:
        print(df.round(4).to_string())

    return df


# ── Cross-chip averaging (shared by the "averaged metrics" cell and the LaTeX table) ──
def _method_family_key(label):
    """Groups a method label the same way regardless of chip -- needed because SG HP
    search's per-chip auto-tuned window means the SAME method ('SG p=2') carries a
    DIFFERENT window in its label on every chip ('SG p=2 (w=31)' vs '(w=27)', ...).
    Averaging by the raw label string would treat those as different methods; this
    strips just the w=.. part so they group together. Every other label's
    hyperparameter (Smoothed's w, Wavelet's mother function) is a fixed constant
    across chips already, so it needs no stripping."""
    m = re.match(r'^(SG p=\d+) \(w=\d+\)$', label)
    return m.group(1) if m else label


def _extract_sg_window(label):
    m = re.match(r'^SG p=\d+ \(w=(\d+)\)$', label)
    return int(m.group(1)) if m else None


def _average_metrics_df(metrics_by_folder, folders, metric_cols=None, show_window=True, return_std=False):
    """Method x metric DataFrame averaged across every folder, grouped by
    _method_family_key (not the raw label) so SG HP search's per-chip window doesn't
    split what's really the same method into separate rows. The displayed SG window
    is the mean of each chip's own optimal_w, rounded to the nearest odd integer
    (matching _ensure_odd) and prefixed with '~' since chips didn't all land on the
    same value -- e.g. 'SG p=2 (w=~29)'. Pass show_window=False to drop the
    window annotation entirely (e.g. for a plain method-name display). Pass
    return_std=True to also get the across-chip std, as a second DataFrame with
    the same (grouped, reindexed, relabeled) index -- for reporting spread
    alongside the mean (e.g. 'mean ± std') via the LaTeX average panel.

    metric_cols: which columns to average -- defaults to every column present in the
    per-folder DataFrames (all 7 metrics compare_all_methods computes); pass a subset
    (e.g. _LATEX_METRIC_COLS) to restrict it."""
    used = [metrics_by_folder[f[0]] for f in folders if f[0] in metrics_by_folder]
    if not used:
        raise ValueError('No folders with metrics to average.')
    cols = metric_cols if metric_cols is not None else list(used[0].columns)
    combined = pd.concat(used)
    family_keys = combined.index.map(_method_family_key)
    grouped = combined.groupby(family_keys)[cols]
    avg = grouped.mean()
    std = grouped.std() if return_std else None

    order, seen, sg_windows = [], set(), {}
    for lbl in used[0].index:
        fam = _method_family_key(lbl)
        if fam not in seen:
            seen.add(fam); order.append(fam)
    for df in used:
        for lbl in df.index:
            w = _extract_sg_window(lbl)
            if w is not None:
                sg_windows.setdefault(_method_family_key(lbl), []).append(w)

    def _display_label(fam):
        if fam in sg_windows and show_window:
            return f'{fam} (w=~{_ensure_odd(round(np.mean(sg_windows[fam])))})'
        return fam

    avg = avg.reindex(order)
    avg.index = [_display_label(f) for f in order]
    if return_std:
        std = std.reindex(order)
        std.index = avg.index
        return avg, std
    return avg


# ── Best-value highlighting (mirrors compare_all_methods' own per-column styling) ──
_METRIC_DIRECTIONS = {
    'SNR (dB)': '\u2191', 'Noise %': '\u2193', 'Fidelity (corr)': '\u2191',
    'Residual AC lag-1': '\u2193', 'TV ratio': '\u2193', '\u0394 TTP': '\u2193',
    'SD_max ratio': '\u21921', 'Curves/s': '\u2191', 'Peak Mem (MB)': '\u2193',
}


def _highlight_best(col, directions=_METRIC_DIRECTIONS):
    d = directions.get(col.name, '\u2191')
    finite = col.dropna()
    if finite.empty:
        return [''] * len(col)
    best_lbl = ((finite - 1.0).abs().idxmin() if d == '\u21921'
                else finite.idxmin()           if d == '\u2193'
                else finite.idxmax())
    return ['background-color: #c8f7c5; font-weight: bold'
            if i == best_lbl else '' for i in col.index]

print('All utility functions loaded.')

All utility functions loaded.

In [5]:
label_maps = config.get_label_mappings(EXP_FOLDER)
results    = {}
folders    = list_folders(EXP_FOLDER)[-6:]

print(f'{DATASET}: {len(folders)} folders')
for folder_name, folder_path in folders:
    print(f'\n─── {folder_name} ───')
    try:
        raw, smoothed, well_labels = load_exp(folder_path)
        print(f'  {raw.shape}')
        results[folder_name] = {
            'raw':         raw,
            'smoothed':    smoothed,
            'denoised':    {w: denoise_all(raw, wavelet=w) for w in WAVELETS},
            'well_labels': well_labels,
            'label_map':   label_maps.get(folder_name, {}),
        }
    except Exception as e:
        print(f'  [ERROR] {e}')

POC_DDM_final: 6 folders

─── D20260825_E00_C00_F4500KHz_U_DDM_05_01 ───

  (17350, 908)

Denoising [sym8]:   0%|          | 0/17350 [00:00<?, ?curve/s]

Denoising [sym8]:   0%|          | 1/17350 [00:00<30:04,  9.61curve/s]

Denoising [sym8]:   2%|▏         | 366/17350 [00:00<00:08, 2114.08curve/s]

Denoising [sym8]:   4%|▍         | 690/17350 [00:00<00:06, 2620.24curve/s]

Denoising [sym8]:   6%|▌         | 1028/17350 [00:00<00:05, 2916.81curve/s]

Denoising [sym8]:   8%|▊         | 1341/17350 [00:00<00:05, 2991.53curve/s]

Denoising [sym8]:  10%|▉         | 1652/17350 [00:00<00:05, 3029.27curve/s]

Denoising [sym8]:  11%|█▏        | 1989/17350 [00:00<00:04, 3139.54curve/s]

Denoising [sym8]:  13%|█▎        | 2330/17350 [00:00<00:04, 3223.31curve/s]

Denoising [sym8]:  15%|█▌        | 2689/17350 [00:00<00:04, 3334.51curve/s]

Denoising [sym8]:  17%|█▋        | 3033/17350 [00:01<00:04, 3365.07curve/s]

Denoising [sym8]:  19%|█▉        | 3370/17350 [00:01<00:04, 3356.22curve/s]

Denoising [sym8]:  21%|██▏       | 3721/17350 [00:01<00:04, 3399.20curve/s]

Denoising [sym8]:  23%|██▎       | 4076/17350 [00:01<00:03, 3444.68curve/s]

Denoising [sym8]:  26%|██▌       | 4434/17350 [00:01<00:03, 3484.74curve/s]

Denoising [sym8]:  28%|██▊       | 4783/17350 [00:01<00:03, 3349.93curve/s]

Denoising [sym8]:  30%|██▉       | 5120/17350 [00:01<00:03, 3257.43curve/s]

Denoising [sym8]:  31%|███▏      | 5463/17350 [00:01<00:03, 3303.50curve/s]

Denoising [sym8]:  34%|███▎      | 5829/17350 [00:01<00:03, 3405.86curve/s]

Denoising [sym8]:  36%|███▌      | 6189/17350 [00:01<00:03, 3461.47curve/s]

Denoising [sym8]:  38%|███▊      | 6538/17350 [00:02<00:03, 3469.49curve/s]

Denoising [sym8]:  40%|███▉      | 6886/17350 [00:02<00:03, 3429.53curve/s]

Denoising [sym8]:  42%|████▏     | 7230/17350 [00:02<00:02, 3392.09curve/s]

Denoising [sym8]:  44%|████▎     | 7585/17350 [00:02<00:02, 3436.26curve/s]

Denoising [sym8]:  46%|████▌     | 7929/17350 [00:02<00:02, 3399.90curve/s]

Denoising [sym8]:  48%|████▊     | 8270/17350 [00:02<00:02, 3384.43curve/s]

Denoising [sym8]:  50%|████▉     | 8609/17350 [00:02<00:02, 3380.48curve/s]

Denoising [sym8]:  52%|█████▏    | 8948/17350 [00:02<00:02, 3309.28curve/s]

Denoising [sym8]:  54%|█████▎    | 9306/17350 [00:02<00:02, 3386.25curve/s]

Denoising [sym8]:  56%|█████▌    | 9646/17350 [00:02<00:02, 3346.12curve/s]

Denoising [sym8]:  58%|█████▊    | 9993/17350 [00:03<00:02, 3382.39curve/s]

Denoising [sym8]:  60%|█████▉    | 10342/17350 [00:03<00:02, 3413.51curve/s]

Denoising [sym8]:  62%|██████▏   | 10684/17350 [00:03<00:01, 3385.72curve/s]

Denoising [sym8]:  64%|██████▎   | 11023/17350 [00:03<00:01, 3365.58curve/s]

Denoising [sym8]:  65%|██████▌   | 11360/17350 [00:03<00:01, 3235.08curve/s]

Denoising [sym8]:  67%|██████▋   | 11703/17350 [00:03<00:01, 3290.91curve/s]

Denoising [sym8]:  69%|██████▉   | 12034/17350 [00:03<00:01, 3259.18curve/s]

Denoising [sym8]:  71%|███████   | 12361/17350 [00:03<00:01, 3232.33curve/s]

Denoising [sym8]:  73%|███████▎  | 12726/17350 [00:03<00:01, 3352.25curve/s]

Denoising [sym8]:  75%|███████▌  | 13086/17350 [00:03<00:01, 3423.85curve/s]

Denoising [sym8]:  77%|███████▋  | 13429/17350 [00:04<00:01, 3408.64curve/s]

Denoising [sym8]:  79%|███████▉  | 13771/17350 [00:04<00:01, 3334.93curve/s]

Denoising [sym8]:  81%|████████▏ | 14126/17350 [00:04<00:00, 3396.26curve/s]

Denoising [sym8]:  83%|████████▎ | 14467/17350 [00:04<00:00, 3321.96curve/s]

Denoising [sym8]:  85%|████████▌ | 14800/17350 [00:04<00:00, 3150.86curve/s]

Denoising [sym8]:  87%|████████▋ | 15125/17350 [00:04<00:00, 3178.78curve/s]

Denoising [sym8]:  89%|████████▉ | 15483/17350 [00:04<00:00, 3294.00curve/s]

Denoising [sym8]:  91%|█████████▏| 15845/17350 [00:04<00:00, 3387.26curve/s]

Denoising [sym8]:  93%|█████████▎| 16200/17350 [00:04<00:00, 3434.27curve/s]

Denoising [sym8]:  95%|█████████▌| 16545/17350 [00:05<00:00, 3413.78curve/s]

Denoising [sym8]:  97%|█████████▋| 16891/17350 [00:05<00:00, 3423.64curve/s]

Denoising [sym8]:  99%|█████████▉| 17234/17350 [00:05<00:00, 3374.03curve/s]

Denoising [sym8]: 100%|██████████| 17350/17350 [00:05<00:00, 3293.78curve/s]

─── D20260825_E00_C00_F4500KHz_U_DDM_06_02 ───

  (16971, 915)

Denoising [sym8]:   0%|          | 0/16971 [00:00<?, ?curve/s]

Denoising [sym8]:   2%|▏         | 292/16971 [00:00<00:05, 2915.92curve/s]

Denoising [sym8]:   4%|▎         | 624/16971 [00:00<00:05, 3150.31curve/s]

Denoising [sym8]:   6%|▌         | 981/16971 [00:00<00:04, 3337.58curve/s]

Denoising [sym8]:   8%|▊         | 1340/16971 [00:00<00:04, 3436.93curve/s]

Denoising [sym8]:  10%|▉         | 1684/16971 [00:00<00:04, 3424.24curve/s]

Denoising [sym8]:  12%|█▏        | 2027/16971 [00:00<00:04, 3340.19curve/s]

Denoising [sym8]:  14%|█▍        | 2362/16971 [00:00<00:04, 3296.06curve/s]

Denoising [sym8]:  16%|█▌        | 2692/16971 [00:00<00:04, 3247.96curve/s]

Denoising [sym8]:  18%|█▊        | 3044/16971 [00:00<00:04, 3328.52curve/s]

Denoising [sym8]:  20%|█▉        | 3378/16971 [00:01<00:04, 3272.03curve/s]

Denoising [sym8]:  22%|██▏       | 3720/16971 [00:01<00:03, 3316.13curve/s]

Denoising [sym8]:  24%|██▍       | 4052/16971 [00:01<00:03, 3289.78curve/s]

Denoising [sym8]:  26%|██▌       | 4418/16971 [00:01<00:03, 3396.74curve/s]

Denoising [sym8]:  28%|██▊       | 4778/16971 [00:01<00:03, 3452.50curve/s]

Denoising [sym8]:  30%|███       | 5124/16971 [00:01<00:03, 3363.86curve/s]

Denoising [sym8]:  32%|███▏      | 5475/16971 [00:01<00:03, 3404.22curve/s]

Denoising [sym8]:  34%|███▍      | 5816/16971 [00:01<00:03, 3375.46curve/s]

Denoising [sym8]:  36%|███▋      | 6168/16971 [00:01<00:03, 3415.63curve/s]

Denoising [sym8]:  38%|███▊      | 6510/16971 [00:01<00:03, 3370.85curve/s]

Denoising [sym8]:  40%|████      | 6859/16971 [00:02<00:02, 3403.98curve/s]

Denoising [sym8]:  42%|████▏     | 7200/16971 [00:02<00:03, 3076.06curve/s]

Denoising [sym8]:  45%|████▍     | 7571/16971 [00:02<00:02, 3250.00curve/s]

Denoising [sym8]:  47%|████▋     | 7902/16971 [00:02<00:02, 3192.68curve/s]

Denoising [sym8]:  48%|████▊     | 8226/16971 [00:02<00:02, 3147.60curve/s]

Denoising [sym8]:  50%|█████     | 8544/16971 [00:02<00:02, 3090.30curve/s]

Denoising [sym8]:  52%|█████▏    | 8855/16971 [00:02<00:02, 3017.63curve/s]

Denoising [sym8]:  54%|█████▍    | 9201/16971 [00:02<00:02, 3141.20curve/s]

Denoising [sym8]:  56%|█████▌    | 9517/16971 [00:02<00:02, 3136.10curve/s]

Denoising [sym8]:  58%|█████▊    | 9832/16971 [00:03<00:02, 3130.06curve/s]

Denoising [sym8]:  60%|█████▉    | 10146/16971 [00:03<00:02, 3074.62curve/s]

Denoising [sym8]:  62%|██████▏   | 10484/16971 [00:03<00:02, 3160.67curve/s]

Denoising [sym8]:  64%|██████▎   | 10809/16971 [00:03<00:01, 3185.91curve/s]

Denoising [sym8]:  66%|██████▌   | 11145/16971 [00:03<00:01, 3236.52curve/s]

Denoising [sym8]:  68%|██████▊   | 11470/16971 [00:03<00:01, 3171.77curve/s]

Denoising [sym8]:  70%|██████▉   | 11825/16971 [00:03<00:01, 3281.62curve/s]

Denoising [sym8]:  72%|███████▏  | 12154/16971 [00:03<00:01, 3184.86curve/s]

Denoising [sym8]:  74%|███████▎  | 12481/16971 [00:03<00:01, 3207.32curve/s]

Denoising [sym8]:  75%|███████▌  | 12803/16971 [00:03<00:01, 3201.69curve/s]

Denoising [sym8]:  77%|███████▋  | 13134/16971 [00:04<00:01, 3232.80curve/s]

Denoising [sym8]:  79%|███████▉  | 13458/16971 [00:04<00:01, 3215.40curve/s]

Denoising [sym8]:  81%|████████  | 13780/16971 [00:04<00:00, 3215.34curve/s]

Denoising [sym8]:  83%|████████▎ | 14149/16971 [00:04<00:00, 3354.28curve/s]

Denoising [sym8]:  85%|████████▌ | 14485/16971 [00:04<00:00, 3313.42curve/s]

Denoising [sym8]:  87%|████████▋ | 14823/16971 [00:04<00:00, 3331.15curve/s]

Denoising [sym8]:  89%|████████▉ | 15180/16971 [00:04<00:00, 3400.99curve/s]

Denoising [sym8]:  91%|█████████▏| 15521/16971 [00:04<00:00, 3262.98curve/s]

Denoising [sym8]:  93%|█████████▎| 15849/16971 [00:04<00:00, 3262.05curve/s]

Denoising [sym8]:  95%|█████████▌| 16177/16971 [00:04<00:00, 3187.16curve/s]

Denoising [sym8]:  97%|█████████▋| 16506/16971 [00:05<00:00, 3215.72curve/s]

Denoising [sym8]:  99%|█████████▉| 16829/16971 [00:05<00:00, 3197.70curve/s]

Denoising [sym8]: 100%|██████████| 16971/16971 [00:05<00:00, 3248.92curve/s]

─── D20260827_E00_C00_F4500KHz_U_DDM_01_final_final ───

  (16381, 869)

Denoising [sym8]:   0%|          | 0/16381 [00:00<?, ?curve/s]

Denoising [sym8]:   2%|▏         | 318/16381 [00:00<00:05, 3172.69curve/s]

Denoising [sym8]:   4%|▍         | 636/16381 [00:00<00:04, 3164.04curve/s]

Denoising [sym8]:   6%|▌         | 953/16381 [00:00<00:04, 3152.96curve/s]

Denoising [sym8]:   8%|▊         | 1323/16381 [00:00<00:04, 3367.93curve/s]

Denoising [sym8]:  10%|█         | 1660/16381 [00:00<00:04, 3303.63curve/s]

Denoising [sym8]:  12%|█▏        | 2027/16381 [00:00<00:04, 3425.29curve/s]

Denoising [sym8]:  15%|█▍        | 2385/16381 [00:00<00:04, 3470.66curve/s]

Denoising [sym8]:  17%|█▋        | 2738/16381 [00:00<00:03, 3486.36curve/s]

Denoising [sym8]:  19%|█▉        | 3087/16381 [00:00<00:03, 3458.83curve/s]

Denoising [sym8]:  21%|██        | 3434/16381 [00:01<00:03, 3393.52curve/s]

Denoising [sym8]:  23%|██▎       | 3789/16381 [00:01<00:03, 3439.40curve/s]

Denoising [sym8]:  25%|██▌       | 4134/16381 [00:01<00:03, 3404.81curve/s]

Denoising [sym8]:  27%|██▋       | 4484/16381 [00:01<00:03, 3431.82curve/s]

Denoising [sym8]:  29%|██▉       | 4828/16381 [00:01<00:03, 3314.13curve/s]

Denoising [sym8]:  32%|███▏      | 5161/16381 [00:01<00:03, 3243.15curve/s]

Denoising [sym8]:  33%|███▎      | 5487/16381 [00:01<00:03, 3212.23curve/s]

Denoising [sym8]:  36%|███▌      | 5832/16381 [00:01<00:03, 3279.45curve/s]

Denoising [sym8]:  38%|███▊      | 6187/16381 [00:01<00:03, 3356.15curve/s]

Denoising [sym8]:  40%|███▉      | 6524/16381 [00:01<00:02, 3322.92curve/s]

Denoising [sym8]:  42%|████▏     | 6861/16381 [00:02<00:02, 3336.72curve/s]

Denoising [sym8]:  44%|████▍     | 7217/16381 [00:02<00:02, 3401.27curve/s]

Denoising [sym8]:  46%|████▌     | 7572/16381 [00:02<00:02, 3443.22curve/s]

Denoising [sym8]:  48%|████▊     | 7917/16381 [00:02<00:02, 3370.72curve/s]

Denoising [sym8]:  50%|█████     | 8266/16381 [00:02<00:02, 3403.14curve/s]

Denoising [sym8]:  53%|█████▎    | 8607/16381 [00:02<00:02, 3262.06curve/s]

Denoising [sym8]:  55%|█████▍    | 8950/16381 [00:02<00:02, 3307.88curve/s]

Denoising [sym8]:  57%|█████▋    | 9287/16381 [00:02<00:02, 3324.82curve/s]

Denoising [sym8]:  59%|█████▉    | 9630/16381 [00:02<00:02, 3353.86curve/s]

Denoising [sym8]:  61%|██████    | 9967/16381 [00:02<00:01, 3323.08curve/s]

Denoising [sym8]:  63%|██████▎   | 10320/16381 [00:03<00:01, 3380.57curve/s]

Denoising [sym8]:  65%|██████▌   | 10664/16381 [00:03<00:01, 3396.39curve/s]

Denoising [sym8]:  67%|██████▋   | 11011/16381 [00:03<00:01, 3417.57curve/s]

Denoising [sym8]:  69%|██████▉   | 11354/16381 [00:03<00:01, 3388.04curve/s]

Denoising [sym8]:  71%|███████▏  | 11706/16381 [00:03<00:01, 3422.41curve/s]

Denoising [sym8]:  74%|███████▎  | 12049/16381 [00:03<00:01, 3380.46curve/s]

Denoising [sym8]:  76%|███████▌  | 12388/16381 [00:03<00:01, 3341.72curve/s]

Denoising [sym8]:  78%|███████▊  | 12734/16381 [00:03<00:01, 3376.14curve/s]

Denoising [sym8]:  80%|███████▉  | 13103/16381 [00:03<00:00, 3466.56curve/s]

Denoising [sym8]:  82%|████████▏ | 13450/16381 [00:04<00:00, 3356.85curve/s]

Denoising [sym8]:  84%|████████▍ | 13819/16381 [00:04<00:00, 3452.29curve/s]

Denoising [sym8]:  86%|████████▋ | 14166/16381 [00:04<00:00, 3333.13curve/s]

Denoising [sym8]:  89%|████████▊ | 14520/16381 [00:04<00:00, 3390.40curve/s]

Denoising [sym8]:  91%|█████████ | 14866/16381 [00:04<00:00, 3407.12curve/s]

Denoising [sym8]:  93%|█████████▎| 15214/16381 [00:04<00:00, 3427.81curve/s]

Denoising [sym8]:  95%|█████████▍| 15558/16381 [00:04<00:00, 3293.79curve/s]

Denoising [sym8]:  97%|█████████▋| 15890/16381 [00:04<00:00, 3299.52curve/s]

Denoising [sym8]:  99%|█████████▉| 16236/16381 [00:04<00:00, 3345.30curve/s]

Denoising [sym8]: 100%|██████████| 16381/16381 [00:04<00:00, 3357.42curve/s]

─── D20260827_E00_C00_F4500KHz_U_DDM_02_final_final ───

  (16638, 905)

Denoising [sym8]:   0%|          | 0/16638 [00:00<?, ?curve/s]

Denoising [sym8]:   2%|▏         | 342/16638 [00:00<00:04, 3416.74curve/s]

Denoising [sym8]:   4%|▍         | 684/16638 [00:00<00:05, 3111.91curve/s]

Denoising [sym8]:   6%|▌         | 1035/16638 [00:00<00:04, 3280.98curve/s]

Denoising [sym8]:   8%|▊         | 1382/16638 [00:00<00:04, 3350.64curve/s]

Denoising [sym8]:  10%|█         | 1725/16638 [00:00<00:04, 3376.20curve/s]

Denoising [sym8]:  13%|█▎        | 2082/16638 [00:00<00:04, 3439.26curve/s]

Denoising [sym8]:  15%|█▍        | 2427/16638 [00:00<00:04, 3357.88curve/s]

Denoising [sym8]:  17%|█▋        | 2764/16638 [00:00<00:04, 3348.79curve/s]

Denoising [sym8]:  19%|█▊        | 3100/16638 [00:00<00:04, 3321.38curve/s]

Denoising [sym8]:  21%|██        | 3433/16638 [00:01<00:04, 3298.45curve/s]

Denoising [sym8]:  23%|██▎       | 3803/16638 [00:01<00:03, 3418.32curve/s]

Denoising [sym8]:  25%|██▍       | 4146/16638 [00:01<00:03, 3291.30curve/s]

Denoising [sym8]:  27%|██▋       | 4492/16638 [00:01<00:03, 3337.74curve/s]

Denoising [sym8]:  29%|██▉       | 4827/16638 [00:01<00:03, 3321.74curve/s]

Denoising [sym8]:  31%|███       | 5174/16638 [00:01<00:03, 3363.32curve/s]

Denoising [sym8]:  33%|███▎      | 5511/16638 [00:01<00:03, 3365.19curve/s]

Denoising [sym8]:  35%|███▌      | 5848/16638 [00:01<00:03, 3344.10curve/s]

Denoising [sym8]:  37%|███▋      | 6184/16638 [00:01<00:03, 3345.74curve/s]

Denoising [sym8]:  39%|███▉      | 6529/16638 [00:01<00:02, 3371.87curve/s]

Denoising [sym8]:  41%|████▏     | 6867/16638 [00:02<00:03, 3251.93curve/s]

Denoising [sym8]:  43%|████▎     | 7214/16638 [00:02<00:02, 3314.11curve/s]

Denoising [sym8]:  45%|████▌     | 7547/16638 [00:02<00:02, 3272.08curve/s]

Denoising [sym8]:  47%|████▋     | 7893/16638 [00:02<00:02, 3325.05curve/s]

Denoising [sym8]:  49%|████▉     | 8227/16638 [00:02<00:02, 3232.81curve/s]

Denoising [sym8]:  51%|█████▏    | 8552/16638 [00:02<00:02, 3217.44curve/s]

Denoising [sym8]:  53%|█████▎    | 8891/16638 [00:02<00:02, 3265.51curve/s]

Denoising [sym8]:  55%|█████▌    | 9227/16638 [00:02<00:02, 3289.63curve/s]

Denoising [sym8]:  58%|█████▊    | 9584/16638 [00:02<00:02, 3370.06curve/s]

Denoising [sym8]:  60%|█████▉    | 9922/16638 [00:03<00:02, 3203.83curve/s]

Denoising [sym8]:  62%|██████▏   | 10245/16638 [00:03<00:02, 3180.70curve/s]

Denoising [sym8]:  64%|██████▎   | 10577/16638 [00:03<00:01, 3219.56curve/s]

Denoising [sym8]:  66%|██████▌   | 10900/16638 [00:03<00:01, 3210.96curve/s]

Denoising [sym8]:  68%|██████▊   | 11236/16638 [00:03<00:01, 3252.51curve/s]

Denoising [sym8]:  70%|██████▉   | 11590/16638 [00:03<00:01, 3335.73curve/s]

Denoising [sym8]:  72%|███████▏  | 11956/16638 [00:03<00:01, 3430.18curve/s]

Denoising [sym8]:  74%|███████▍  | 12316/16638 [00:03<00:01, 3474.97curve/s]

Denoising [sym8]:  76%|███████▌  | 12679/16638 [00:03<00:01, 3518.88curve/s]

Denoising [sym8]:  78%|███████▊  | 13032/16638 [00:03<00:01, 3423.79curve/s]

Denoising [sym8]:  80%|████████  | 13376/16638 [00:04<00:00, 3343.39curve/s]

Denoising [sym8]:  82%|████████▏ | 13723/16638 [00:04<00:00, 3378.13curve/s]

Denoising [sym8]:  85%|████████▍ | 14076/16638 [00:04<00:00, 3421.16curve/s]

Denoising [sym8]:  87%|████████▋ | 14419/16638 [00:04<00:00, 3386.56curve/s]

Denoising [sym8]:  89%|████████▊ | 14766/16638 [00:04<00:00, 3410.94curve/s]

Denoising [sym8]:  91%|█████████ | 15108/16638 [00:04<00:00, 3397.26curve/s]

Denoising [sym8]:  93%|█████████▎| 15457/16638 [00:04<00:00, 3417.82curve/s]

Denoising [sym8]:  95%|█████████▍| 15799/16638 [00:04<00:00, 3365.31curve/s]

Denoising [sym8]:  97%|█████████▋| 16136/16638 [00:04<00:00, 3225.18curve/s]

Denoising [sym8]:  99%|█████████▉| 16460/16638 [00:04<00:00, 3134.15curve/s]

Denoising [sym8]: 100%|██████████| 16638/16638 [00:05<00:00, 3313.18curve/s]

─── D20260827_E00_C00_F4500KHz_U_DDM_03_final_final ───

  (16754, 560)

Denoising [sym8]:   0%|          | 0/16754 [00:00<?, ?curve/s]

Denoising [sym8]:   2%|▏         | 350/16754 [00:00<00:04, 3495.61curve/s]

Denoising [sym8]:   4%|▍         | 723/16754 [00:00<00:04, 3633.22curve/s]

Denoising [sym8]:   6%|▋         | 1087/16754 [00:00<00:04, 3484.59curve/s]

Denoising [sym8]:   9%|▊         | 1437/16754 [00:00<00:04, 3450.42curve/s]

Denoising [sym8]:  11%|█         | 1803/16754 [00:00<00:04, 3521.38curve/s]

Denoising [sym8]:  13%|█▎        | 2156/16754 [00:00<00:04, 3455.51curve/s]

Denoising [sym8]:  15%|█▍        | 2502/16754 [00:00<00:04, 3399.33curve/s]

Denoising [sym8]:  17%|█▋        | 2850/16754 [00:00<00:04, 3422.65curve/s]

Denoising [sym8]:  19%|█▉        | 3197/16754 [00:00<00:03, 3437.13curve/s]

Denoising [sym8]:  21%|██▏       | 3585/16754 [00:01<00:03, 3570.85curve/s]

Denoising [sym8]:  24%|██▎       | 3974/16754 [00:01<00:03, 3666.18curve/s]

Denoising [sym8]:  26%|██▌       | 4346/16754 [00:01<00:03, 3681.28curve/s]

Denoising [sym8]:  28%|██▊       | 4715/16754 [00:01<00:03, 3643.82curve/s]

Denoising [sym8]:  30%|███       | 5080/16754 [00:01<00:03, 3432.26curve/s]

Denoising [sym8]:  32%|███▏      | 5426/16754 [00:01<00:03, 3358.08curve/s]

Denoising [sym8]:  34%|███▍      | 5764/16754 [00:01<00:03, 3289.46curve/s]

Denoising [sym8]:  37%|███▋      | 6137/16754 [00:01<00:03, 3413.20curve/s]

Denoising [sym8]:  39%|███▊      | 6485/16754 [00:01<00:02, 3432.15curve/s]

Denoising [sym8]:  41%|████      | 6868/16754 [00:01<00:02, 3546.31curve/s]

Denoising [sym8]:  43%|████▎     | 7246/16754 [00:02<00:02, 3615.00curve/s]

Denoising [sym8]:  45%|████▌     | 7609/16754 [00:02<00:02, 3563.83curve/s]

Denoising [sym8]:  48%|████▊     | 7971/16754 [00:02<00:02, 3579.41curve/s]

Denoising [sym8]:  50%|████▉     | 8330/16754 [00:02<00:02, 3574.11curve/s]

Denoising [sym8]:  52%|█████▏    | 8693/16754 [00:02<00:02, 3589.52curve/s]

Denoising [sym8]:  54%|█████▍    | 9053/16754 [00:02<00:02, 3415.61curve/s]

Denoising [sym8]:  56%|█████▋    | 9431/16754 [00:02<00:02, 3519.05curve/s]

Denoising [sym8]:  59%|█████▊    | 9809/16754 [00:02<00:01, 3592.94curve/s]

Denoising [sym8]:  61%|██████    | 10193/16754 [00:02<00:01, 3664.00curve/s]

Denoising [sym8]:  63%|██████▎   | 10561/16754 [00:03<00:01, 3561.10curve/s]

Denoising [sym8]:  65%|██████▌   | 10919/16754 [00:03<00:01, 3490.07curve/s]

Denoising [sym8]:  67%|██████▋   | 11270/16754 [00:03<00:01, 3375.06curve/s]

Denoising [sym8]:  69%|██████▉   | 11616/16754 [00:03<00:01, 3399.11curve/s]

Denoising [sym8]:  71%|███████▏  | 11975/16754 [00:03<00:01, 3452.65curve/s]

Denoising [sym8]:  74%|███████▎  | 12322/16754 [00:03<00:01, 3428.04curve/s]

Denoising [sym8]:  76%|███████▌  | 12679/16754 [00:03<00:01, 3467.18curve/s]

Denoising [sym8]:  78%|███████▊  | 13027/16754 [00:03<00:01, 3421.53curve/s]

Denoising [sym8]:  80%|███████▉  | 13370/16754 [00:03<00:01, 3378.91curve/s]

Denoising [sym8]:  82%|████████▏ | 13755/16754 [00:03<00:00, 3513.42curve/s]

Denoising [sym8]:  84%|████████▍ | 14136/16754 [00:04<00:00, 3598.67curve/s]

Denoising [sym8]:  87%|████████▋ | 14497/16754 [00:04<00:00, 3561.42curve/s]

Denoising [sym8]:  89%|████████▉ | 14871/16754 [00:04<00:00, 3612.90curve/s]

Denoising [sym8]:  91%|█████████ | 15233/16754 [00:04<00:00, 3548.32curve/s]

Denoising [sym8]:  93%|█████████▎| 15589/16754 [00:04<00:00, 3533.15curve/s]

Denoising [sym8]:  95%|█████████▌| 15946/16754 [00:04<00:00, 3541.54curve/s]

Denoising [sym8]:  97%|█████████▋| 16313/16754 [00:04<00:00, 3577.98curve/s]

Denoising [sym8]: 100%|█████████▉| 16672/16754 [00:04<00:00, 3555.39curve/s]

Denoising [sym8]: 100%|██████████| 16754/16754 [00:04<00:00, 3510.94curve/s]

─── D20260827_E00_C00_F4500KHz_U_DDM_04_final_final ───

  (16480, 868)

Denoising [sym8]:   0%|          | 0/16480 [00:00<?, ?curve/s]

Denoising [sym8]:   2%|▏         | 332/16480 [00:00<00:04, 3315.79curve/s]

Denoising [sym8]:   4%|▍         | 664/16480 [00:00<00:04, 3189.84curve/s]

Denoising [sym8]:   6%|▌         | 984/16480 [00:00<00:04, 3113.14curve/s]

Denoising [sym8]:   8%|▊         | 1331/16480 [00:00<00:04, 3245.21curve/s]

Denoising [sym8]:  10%|█         | 1666/16480 [00:00<00:04, 3278.64curve/s]

Denoising [sym8]:  12%|█▏        | 2012/16480 [00:00<00:04, 3336.61curve/s]

Denoising [sym8]:  14%|█▍        | 2346/16480 [00:00<00:04, 3242.88curve/s]

Denoising [sym8]:  16%|█▌        | 2677/16480 [00:00<00:04, 3262.91curve/s]

Denoising [sym8]:  18%|█▊        | 3004/16480 [00:00<00:04, 3212.23curve/s]

Denoising [sym8]:  20%|██        | 3326/16480 [00:01<00:04, 3096.46curve/s]

Denoising [sym8]:  22%|██▏       | 3677/16480 [00:01<00:03, 3215.60curve/s]

Denoising [sym8]:  24%|██▍       | 4025/16480 [00:01<00:03, 3292.21curve/s]

Denoising [sym8]:  27%|██▋       | 4382/16480 [00:01<00:03, 3373.64curve/s]

Denoising [sym8]:  29%|██▊       | 4721/16480 [00:01<00:03, 3278.45curve/s]

Denoising [sym8]:  31%|███       | 5078/16480 [00:01<00:03, 3359.66curve/s]

Denoising [sym8]:  33%|███▎      | 5415/16480 [00:01<00:03, 3263.97curve/s]

Denoising [sym8]:  35%|███▍      | 5755/16480 [00:01<00:03, 3302.61curve/s]

Denoising [sym8]:  37%|███▋      | 6089/16480 [00:01<00:03, 3311.05curve/s]

Denoising [sym8]:  39%|███▉      | 6428/16480 [00:01<00:03, 3333.68curve/s]

Denoising [sym8]:  41%|████▏     | 6801/16480 [00:02<00:02, 3450.72curve/s]

Denoising [sym8]:  43%|████▎     | 7147/16480 [00:02<00:02, 3388.36curve/s]

Denoising [sym8]:  45%|████▌     | 7487/16480 [00:02<00:02, 3285.90curve/s]

Denoising [sym8]:  48%|████▊     | 7837/16480 [00:02<00:02, 3345.55curve/s]

Denoising [sym8]:  50%|████▉     | 8202/16480 [00:02<00:02, 3432.16curve/s]

Denoising [sym8]:  52%|█████▏    | 8552/16480 [00:02<00:02, 3448.43curve/s]

Denoising [sym8]:  54%|█████▍    | 8909/16480 [00:02<00:02, 3482.73curve/s]

Denoising [sym8]:  56%|█████▌    | 9267/16480 [00:02<00:02, 3508.72curve/s]

Denoising [sym8]:  58%|█████▊    | 9619/16480 [00:02<00:01, 3504.76curve/s]

Denoising [sym8]:  60%|██████    | 9970/16480 [00:02<00:01, 3433.64curve/s]

Denoising [sym8]:  63%|██████▎   | 10314/16480 [00:03<00:01, 3423.13curve/s]

Denoising [sym8]:  65%|██████▍   | 10657/16480 [00:03<00:01, 3405.92curve/s]

Denoising [sym8]:  67%|██████▋   | 10998/16480 [00:03<00:01, 3381.27curve/s]

Denoising [sym8]:  69%|██████▉   | 11337/16480 [00:03<00:01, 3271.70curve/s]

Denoising [sym8]:  71%|███████   | 11706/16480 [00:03<00:01, 3390.62curve/s]

Denoising [sym8]:  73%|███████▎  | 12052/16480 [00:03<00:01, 3409.71curve/s]

Denoising [sym8]:  75%|███████▌  | 12423/16480 [00:03<00:01, 3496.31curve/s]

Denoising [sym8]:  78%|███████▊  | 12774/16480 [00:03<00:01, 3432.86curve/s]

Denoising [sym8]:  80%|███████▉  | 13126/16480 [00:03<00:00, 3457.49curve/s]

Denoising [sym8]:  82%|████████▏ | 13473/16480 [00:04<00:00, 3416.36curve/s]

Denoising [sym8]:  84%|████████▍ | 13816/16480 [00:04<00:00, 3346.72curve/s]

Denoising [sym8]:  86%|████████▌ | 14172/16480 [00:04<00:00, 3405.84curve/s]

Denoising [sym8]:  88%|████████▊ | 14514/16480 [00:04<00:00, 3299.73curve/s]

Denoising [sym8]:  90%|█████████ | 14845/16480 [00:04<00:00, 3283.26curve/s]

Denoising [sym8]:  92%|█████████▏| 15174/16480 [00:04<00:00, 3241.75curve/s]

Denoising [sym8]:  94%|█████████▍| 15515/16480 [00:04<00:00, 3288.55curve/s]

Denoising [sym8]:  96%|█████████▋| 15862/16480 [00:04<00:00, 3339.17curve/s]

Denoising [sym8]:  98%|█████████▊| 16197/16480 [00:04<00:00, 3341.12curve/s]

Denoising [sym8]: 100%|██████████| 16480/16480 [00:04<00:00, 3339.34curve/s]

---
## Savitzky-Golay Smoothing

Fits a polynomial of degree $p$ to each sliding window of $w$ points. Unlike moving
average ($p=1$), it preserves peaks and the S-curve shape. `SG_OPTIMAL_W` above is the
current chosen window (fixed, not re-swept in this notebook).

---
## Hyperparameter Search (per chip)

SG (polyorder × window) and Wavelet (mother function) each use the same derivative-test
sweep (`_derivative_scores` / `_sweet_spot`) to auto-select their window/candidate per
chip — this is what feeds the `sg_p2/p3/p4` and `wv_sym4/sym6/sym8` rows in the table below.

In [6]:
# ── SG HP Search: polyorder × window sweep ───────────────────────────────────
# Saves results[folder]['sg_p{poly}'] — re-running skips cached entries.

for folder_name, _ in folders:
    if folder_name not in results:
        continue
    r   = results[folder_name]
    raw = r['raw']
    T   = raw.shape[1]

    sg_windows = np.unique(np.array(
        [_ensure_odd(int(w)) for w in np.linspace(5, max(7, int(T * 0.25)), 40)]
    ))
    sg_windows = sg_windows[sg_windows >= 5]

    print(f'\n{folder_name}  (T={T})')
    for poly in SG_POLYORDERS:
        key = f'sg_p{poly}'
        if key in r:
            d = r[key]
            print(f'  SG p={poly}: cached  optimal_w={d["optimal_w"]}  '
                  f'SNR={d["metrics"]["snr"]:.1f}dB')
            continue
        fn       = lambda c, w, p=poly: apply_sg(c, w, p)
        prs, ros = _derivative_scores(raw, sg_windows.astype(float), fn)
        opt_w    = int(_sweet_spot(sg_windows.astype(float), ros))
        den      = apply_sg(raw, opt_w, poly)
        m        = _full_metrics(raw, den)
        r[key]   = dict(windows=sg_windows, prs=prs, ros=ros,
                        optimal_w=opt_w, denoised=den, metrics=m)
        print(f'  SG p={poly}: optimal_w={opt_w}  SNR={m["snr"]:.1f}dB  '
              f'TV={m["tv"]:.3f}  corr={m["corr"]:.4f}')

print('\nDone. Keys: sg_p2, sg_p3, sg_p4')

D20260825_E00_C00_F4500KHz_U_DDM_05_01  (T=908)

  SG p=2: optimal_w=113  SNR=13.9dB  TV=0.028  corr=0.9741

  SG p=3: optimal_w=113  SNR=13.9dB  TV=0.029  corr=0.9743

  SG p=4: optimal_w=113  SNR=14.2dB  TV=0.035  corr=0.9757

D20260825_E00_C00_F4500KHz_U_DDM_06_02  (T=915)

  SG p=2: optimal_w=113  SNR=10.9dB  TV=0.026  corr=0.9394

  SG p=3: optimal_w=113  SNR=10.9dB  TV=0.027  corr=0.9398

  SG p=4: optimal_w=113  SNR=11.2dB  TV=0.033  corr=0.9431

D20260827_E00_C00_F4500KHz_U_DDM_01_final_final  (T=869)

  SG p=2: optimal_w=109  SNR=15.0dB  TV=0.032  corr=0.9808

  SG p=3: optimal_w=109  SNR=15.0dB  TV=0.033  corr=0.9810

  SG p=4: optimal_w=109  SNR=15.3dB  TV=0.038  corr=0.9820

D20260827_E00_C00_F4500KHz_U_DDM_02_final_final  (T=905)

  SG p=2: optimal_w=113  SNR=16.7dB  TV=0.035  corr=0.9845

  SG p=3: optimal_w=113  SNR=16.7dB  TV=0.036  corr=0.9846

  SG p=4: optimal_w=113  SNR=17.0dB  TV=0.041  corr=0.9853

D20260827_E00_C00_F4500KHz_U_DDM_03_final_final  (T=560)

  SG p=2: optimal_w=71  SNR=12.8dB  TV=0.042  corr=0.9569

  SG p=3: optimal_w=71  SNR=12.8dB  TV=0.043  corr=0.9573

  SG p=4: optimal_w=71  SNR=13.1dB  TV=0.052  corr=0.9599

D20260827_E00_C00_F4500KHz_U_DDM_04_final_final  (T=868)

  SG p=2: optimal_w=109  SNR=13.0dB  TV=0.029  corr=0.9709

  SG p=3: optimal_w=109  SNR=13.0dB  TV=0.030  corr=0.9712

  SG p=4: optimal_w=109  SNR=13.3dB  TV=0.036  corr=0.9726

Done. Keys: sg_p2, sg_p3, sg_p4

In [7]:
# ── Wavelet HP Search: mother function comparison ─────────────────────────────
# Saves results[folder]['wv_<name>'] — re-running skips cached entries.

for folder_name, _ in folders:
    if folder_name not in results:
        continue
    r   = results[folder_name]
    raw = r['raw']
    T   = raw.shape[1]
    print(f'\n{folder_name}  (T={T})')

    for wv in WAVELET_CANDIDATES:
        key = f'wv_{wv}'
        if key in r:
            print(f'  Wavelet {wv}: cached')
            continue
        if wv in r.get('denoised', {}):
            den    = r['denoised'][wv]
            r[key] = dict(denoised=den, metrics=_full_metrics(raw, den), is_ref=True)
            print(f'  Wavelet {wv}: (already in WAVELETS)  SNR={r[key]["metrics"]["snr"]:.1f}dB')
            continue
        try:
            if pywt.Wavelet(wv).dec_len > T:
                print(f'  Wavelet {wv}: skip (filter > signal length)')
                continue
            den    = denoise_all(raw, wv)
            r[key] = dict(denoised=den, metrics=_full_metrics(raw, den), is_ref=False)
            m      = r[key]['metrics']
            print(f'  Wavelet {wv}: SNR={m["snr"]:.1f}dB  TV={m["tv"]:.3f}  '
                  f'corr={m["corr"]:.4f}')
        except Exception as e:
            print(f'  Wavelet {wv}: ERROR — {e}')

print('\nDone. Keys: wv_<name> for each candidate.')

D20260825_E00_C00_F4500KHz_U_DDM_05_01  (T=908)

Denoising [sym4]:   0%|          | 0/17350 [00:00<?, ?curve/s]

Denoising [sym4]:   2%|▏         | 271/17350 [00:00<00:06, 2706.65curve/s]

Denoising [sym4]:   3%|▎         | 573/17350 [00:00<00:05, 2886.89curve/s]

Denoising [sym4]:   5%|▌         | 880/17350 [00:00<00:05, 2967.28curve/s]

Denoising [sym4]:   7%|▋         | 1177/17350 [00:00<00:05, 2894.01curve/s]

Denoising [sym4]:   9%|▊         | 1482/17350 [00:00<00:05, 2947.69curve/s]

Denoising [sym4]:  10%|█         | 1778/17350 [00:00<00:05, 2872.39curve/s]

Denoising [sym4]:  12%|█▏        | 2086/17350 [00:00<00:05, 2937.96curve/s]

Denoising [sym4]:  14%|█▍        | 2400/17350 [00:00<00:04, 3000.31curve/s]

Denoising [sym4]:  16%|█▌        | 2701/17350 [00:00<00:04, 2961.30curve/s]

Denoising [sym4]:  17%|█▋        | 2998/17350 [00:01<00:05, 2831.02curve/s]

Denoising [sym4]:  19%|█▉        | 3312/17350 [00:01<00:04, 2920.51curve/s]

Denoising [sym4]:  21%|██        | 3611/17350 [00:01<00:04, 2939.90curve/s]

Denoising [sym4]:  23%|██▎       | 3923/17350 [00:01<00:04, 2992.60curve/s]

Denoising [sym4]:  24%|██▍       | 4235/17350 [00:01<00:04, 3027.84curve/s]

Denoising [sym4]:  26%|██▋       | 4557/17350 [00:01<00:04, 3083.96curve/s]

Denoising [sym4]:  28%|██▊       | 4867/17350 [00:01<00:04, 3087.98curve/s]

Denoising [sym4]:  30%|██▉       | 5199/17350 [00:01<00:03, 3156.63curve/s]

Denoising [sym4]:  32%|███▏      | 5515/17350 [00:01<00:03, 2973.41curve/s]

Denoising [sym4]:  34%|███▎      | 5830/17350 [00:01<00:03, 3021.67curve/s]

Denoising [sym4]:  35%|███▌      | 6159/17350 [00:02<00:03, 3098.55curve/s]

Denoising [sym4]:  37%|███▋      | 6471/17350 [00:02<00:03, 2925.33curve/s]

Denoising [sym4]:  39%|███▉      | 6767/17350 [00:02<00:03, 2856.38curve/s]

Denoising [sym4]:  41%|████      | 7085/17350 [00:02<00:03, 2947.64curve/s]

Denoising [sym4]:  43%|████▎     | 7395/17350 [00:02<00:03, 2989.67curve/s]

Denoising [sym4]:  44%|████▍     | 7715/17350 [00:02<00:03, 3047.12curve/s]

Denoising [sym4]:  46%|████▌     | 8021/17350 [00:02<00:03, 2939.34curve/s]

Denoising [sym4]:  48%|████▊     | 8320/17350 [00:02<00:03, 2951.87curve/s]

Denoising [sym4]:  50%|████▉     | 8647/17350 [00:02<00:02, 3043.59curve/s]

Denoising [sym4]:  52%|█████▏    | 8953/17350 [00:03<00:02, 3019.50curve/s]

Denoising [sym4]:  53%|█████▎    | 9256/17350 [00:03<00:02, 2996.74curve/s]

Denoising [sym4]:  55%|█████▌    | 9569/17350 [00:03<00:02, 3035.57curve/s]

Denoising [sym4]:  57%|█████▋    | 9874/17350 [00:03<00:02, 3007.16curve/s]

Denoising [sym4]:  59%|█████▊    | 10176/17350 [00:03<00:02, 2905.00curve/s]

Denoising [sym4]:  60%|██████    | 10488/17350 [00:03<00:02, 2966.50curve/s]

Denoising [sym4]:  62%|██████▏   | 10786/17350 [00:03<00:02, 2892.76curve/s]

Denoising [sym4]:  64%|██████▍   | 11077/17350 [00:03<00:02, 2787.13curve/s]

Denoising [sym4]:  66%|██████▌   | 11389/17350 [00:03<00:02, 2880.56curve/s]

Denoising [sym4]:  67%|██████▋   | 11683/17350 [00:03<00:01, 2895.91curve/s]

Denoising [sym4]:  69%|██████▉   | 12000/17350 [00:04<00:01, 2974.17curve/s]

Denoising [sym4]:  71%|███████   | 12299/17350 [00:04<00:01, 2941.30curve/s]

Denoising [sym4]:  73%|███████▎  | 12594/17350 [00:04<00:01, 2921.87curve/s]

Denoising [sym4]:  74%|███████▍  | 12895/17350 [00:04<00:01, 2945.91curve/s]

Denoising [sym4]:  76%|███████▌  | 13190/17350 [00:04<00:01, 2846.84curve/s]

Denoising [sym4]:  78%|███████▊  | 13486/17350 [00:04<00:01, 2878.87curve/s]

Denoising [sym4]:  79%|███████▉  | 13781/17350 [00:04<00:01, 2899.46curve/s]

Denoising [sym4]:  81%|████████  | 14083/17350 [00:04<00:01, 2930.50curve/s]

Denoising [sym4]:  83%|████████▎ | 14377/17350 [00:04<00:01, 2875.31curve/s]

Denoising [sym4]:  85%|████████▍ | 14666/17350 [00:04<00:00, 2764.98curve/s]

Denoising [sym4]:  86%|████████▌ | 14963/17350 [00:05<00:00, 2821.69curve/s]

Denoising [sym4]:  88%|████████▊ | 15282/17350 [00:05<00:00, 2928.08curve/s]

Denoising [sym4]:  90%|████████▉ | 15576/17350 [00:05<00:00, 2904.89curve/s]

Denoising [sym4]:  91%|█████████▏| 15868/17350 [00:05<00:00, 2830.91curve/s]

Denoising [sym4]:  93%|█████████▎| 16152/17350 [00:05<00:00, 2804.80curve/s]

Denoising [sym4]:  95%|█████████▍| 16434/17350 [00:05<00:00, 2782.45curve/s]

Denoising [sym4]:  97%|█████████▋| 16752/17350 [00:05<00:00, 2896.04curve/s]

Denoising [sym4]:  98%|█████████▊| 17055/17350 [00:05<00:00, 2934.45curve/s]

Denoising [sym4]: 100%|██████████| 17350/17350 [00:05<00:00, 2937.68curve/s]

  Wavelet sym4: SNR=13.7dB  TV=0.023  corr=0.9731

Denoising [sym6]:   0%|          | 0/17350 [00:00<?, ?curve/s]

Denoising [sym6]:   2%|▏         | 339/17350 [00:00<00:05, 3388.51curve/s]

Denoising [sym6]:   4%|▍         | 678/17350 [00:00<00:05, 3301.30curve/s]

Denoising [sym6]:   6%|▌         | 1009/17350 [00:00<00:05, 3244.44curve/s]

Denoising [sym6]:   8%|▊         | 1334/17350 [00:00<00:05, 3195.75curve/s]

Denoising [sym6]:  10%|▉         | 1654/17350 [00:00<00:05, 3023.41curve/s]

Denoising [sym6]:  11%|█▏        | 1962/17350 [00:00<00:05, 3040.69curve/s]

Denoising [sym6]:  13%|█▎        | 2286/17350 [00:00<00:04, 3103.26curve/s]

Denoising [sym6]:  15%|█▍        | 2598/17350 [00:00<00:04, 3071.02curve/s]

Denoising [sym6]:  17%|█▋        | 2924/17350 [00:00<00:04, 3128.15curve/s]

Denoising [sym6]:  19%|█▊        | 3238/17350 [00:01<00:04, 3102.76curve/s]

Denoising [sym6]:  20%|██        | 3549/17350 [00:01<00:04, 3068.26curve/s]

Denoising [sym6]:  22%|██▏       | 3876/17350 [00:01<00:04, 3127.50curve/s]

Denoising [sym6]:  24%|██▍       | 4190/17350 [00:01<00:04, 2985.11curve/s]

Denoising [sym6]:  26%|██▌       | 4523/17350 [00:01<00:04, 3083.27curve/s]

Denoising [sym6]:  28%|██▊       | 4858/17350 [00:01<00:03, 3158.36curve/s]

Denoising [sym6]:  30%|██▉       | 5176/17350 [00:01<00:04, 3028.53curve/s]

Denoising [sym6]:  32%|███▏      | 5481/17350 [00:01<00:03, 3023.85curve/s]

Denoising [sym6]:  33%|███▎      | 5801/17350 [00:01<00:03, 3072.32curve/s]

Denoising [sym6]:  35%|███▌      | 6110/17350 [00:01<00:03, 3027.30curve/s]

Denoising [sym6]:  37%|███▋      | 6455/17350 [00:02<00:03, 3150.42curve/s]

Denoising [sym6]:  39%|███▉      | 6775/17350 [00:02<00:03, 3163.52curve/s]

Denoising [sym6]:  41%|████      | 7093/17350 [00:02<00:03, 3123.88curve/s]

Denoising [sym6]:  43%|████▎     | 7406/17350 [00:02<00:03, 3121.00curve/s]

Denoising [sym6]:  44%|████▍     | 7719/17350 [00:02<00:03, 3102.88curve/s]

Denoising [sym6]:  46%|████▋     | 8030/17350 [00:02<00:03, 2946.29curve/s]

Denoising [sym6]:  48%|████▊     | 8336/17350 [00:02<00:03, 2976.71curve/s]

Denoising [sym6]:  50%|████▉     | 8668/17350 [00:02<00:02, 3074.01curve/s]

Denoising [sym6]:  52%|█████▏    | 8977/17350 [00:02<00:02, 3045.72curve/s]

Denoising [sym6]:  54%|█████▎    | 9283/17350 [00:03<00:02, 2957.66curve/s]

Denoising [sym6]:  55%|█████▌    | 9593/17350 [00:03<00:02, 2997.40curve/s]

Denoising [sym6]:  57%|█████▋    | 9926/17350 [00:03<00:02, 3093.71curve/s]

Denoising [sym6]:  59%|█████▉    | 10248/17350 [00:03<00:02, 3128.97curve/s]

Denoising [sym6]:  61%|██████    | 10562/17350 [00:03<00:02, 3093.88curve/s]

Denoising [sym6]:  63%|██████▎   | 10888/17350 [00:03<00:02, 3142.08curve/s]

Denoising [sym6]:  65%|██████▍   | 11204/17350 [00:03<00:01, 3147.23curve/s]

Denoising [sym6]:  66%|██████▋   | 11533/17350 [00:03<00:01, 3189.42curve/s]

Denoising [sym6]:  68%|██████▊   | 11853/17350 [00:03<00:01, 3185.14curve/s]

Denoising [sym6]:  70%|███████   | 12183/17350 [00:03<00:01, 3216.74curve/s]

Denoising [sym6]:  72%|███████▏  | 12505/17350 [00:04<00:01, 3188.50curve/s]

Denoising [sym6]:  74%|███████▍  | 12824/17350 [00:04<00:01, 3132.85curve/s]

Denoising [sym6]:  76%|███████▌  | 13141/17350 [00:04<00:01, 3142.41curve/s]

Denoising [sym6]:  78%|███████▊  | 13456/17350 [00:04<00:01, 3055.87curve/s]

Denoising [sym6]:  79%|███████▉  | 13763/17350 [00:04<00:01, 3028.80curve/s]

Denoising [sym6]:  81%|████████  | 14070/17350 [00:04<00:01, 3038.65curve/s]

Denoising [sym6]:  83%|████████▎ | 14378/17350 [00:04<00:00, 3047.86curve/s]

Denoising [sym6]:  85%|████████▍ | 14704/17350 [00:04<00:00, 3108.03curve/s]

Denoising [sym6]:  87%|████████▋ | 15016/17350 [00:04<00:00, 3051.89curve/s]

Denoising [sym6]:  88%|████████▊ | 15353/17350 [00:04<00:00, 3144.76curve/s]

Denoising [sym6]:  90%|█████████ | 15668/17350 [00:05<00:00, 3121.21curve/s]

Denoising [sym6]:  92%|█████████▏| 15981/17350 [00:05<00:00, 3100.22curve/s]

Denoising [sym6]:  94%|█████████▍| 16295/17350 [00:05<00:00, 3111.47curve/s]

Denoising [sym6]:  96%|█████████▌| 16614/17350 [00:05<00:00, 3132.60curve/s]

Denoising [sym6]:  98%|█████████▊| 16928/17350 [00:05<00:00, 3025.72curve/s]

Denoising [sym6]:  99%|█████████▉| 17241/17350 [00:05<00:00, 3053.56curve/s]

Denoising [sym6]: 100%|██████████| 17350/17350 [00:05<00:00, 3092.59curve/s]

  Wavelet sym6: SNR=13.9dB  TV=0.025  corr=0.9744

  Wavelet sym8: (already in WAVELETS)  SNR=14.2dB

D20260825_E00_C00_F4500KHz_U_DDM_06_02  (T=915)

Denoising [sym4]:   0%|          | 0/16971 [00:00<?, ?curve/s]

Denoising [sym4]:   2%|▏         | 299/16971 [00:00<00:05, 2988.38curve/s]

Denoising [sym4]:   4%|▎         | 628/16971 [00:00<00:05, 3164.31curve/s]

Denoising [sym4]:   6%|▌         | 945/16971 [00:00<00:05, 3111.59curve/s]

Denoising [sym4]:   7%|▋         | 1257/16971 [00:00<00:05, 2994.47curve/s]

Denoising [sym4]:   9%|▉         | 1574/16971 [00:00<00:05, 3055.23curve/s]

Denoising [sym4]:  11%|█         | 1896/16971 [00:00<00:04, 3107.83curve/s]

Denoising [sym4]:  13%|█▎        | 2208/16971 [00:00<00:04, 3004.99curve/s]

Denoising [sym4]:  15%|█▍        | 2512/16971 [00:00<00:04, 3014.53curve/s]

Denoising [sym4]:  17%|█▋        | 2815/16971 [00:00<00:04, 3014.67curve/s]

Denoising [sym4]:  19%|█▊        | 3143/16971 [00:01<00:04, 3094.15curve/s]

Denoising [sym4]:  20%|██        | 3453/16971 [00:01<00:04, 2994.92curve/s]

Denoising [sym4]:  22%|██▏       | 3754/16971 [00:01<00:04, 2980.32curve/s]

Denoising [sym4]:  24%|██▍       | 4053/16971 [00:01<00:04, 2942.39curve/s]

Denoising [sym4]:  26%|██▌       | 4367/16971 [00:01<00:04, 2998.18curve/s]

Denoising [sym4]:  28%|██▊       | 4684/16971 [00:01<00:04, 3046.43curve/s]

Denoising [sym4]:  29%|██▉       | 4990/16971 [00:01<00:03, 3041.85curve/s]

Denoising [sym4]:  31%|███       | 5295/16971 [00:01<00:03, 2962.13curve/s]

Denoising [sym4]:  33%|███▎      | 5592/16971 [00:01<00:03, 2934.81curve/s]

Denoising [sym4]:  35%|███▍      | 5926/16971 [00:01<00:03, 3051.80curve/s]

Denoising [sym4]:  37%|███▋      | 6232/16971 [00:02<00:03, 2978.39curve/s]

Denoising [sym4]:  38%|███▊      | 6531/16971 [00:02<00:03, 2961.69curve/s]

Denoising [sym4]:  40%|████      | 6837/16971 [00:02<00:03, 2989.80curve/s]

Denoising [sym4]:  42%|████▏     | 7137/16971 [00:02<00:03, 2951.70curve/s]

Denoising [sym4]:  44%|████▍     | 7433/16971 [00:02<00:03, 2862.34curve/s]

Denoising [sym4]:  46%|████▌     | 7722/16971 [00:02<00:03, 2867.97curve/s]

Denoising [sym4]:  47%|████▋     | 8010/16971 [00:02<00:03, 2806.26curve/s]

Denoising [sym4]:  49%|████▉     | 8320/16971 [00:02<00:02, 2891.00curve/s]

Denoising [sym4]:  51%|█████     | 8610/16971 [00:02<00:02, 2818.25curve/s]

Denoising [sym4]:  52%|█████▏    | 8907/16971 [00:03<00:02, 2861.59curve/s]

Denoising [sym4]:  54%|█████▍    | 9199/16971 [00:03<00:02, 2877.36curve/s]

Denoising [sym4]:  56%|█████▌    | 9502/16971 [00:03<00:02, 2920.89curve/s]

Denoising [sym4]:  58%|█████▊    | 9795/16971 [00:03<00:02, 2917.16curve/s]

Denoising [sym4]:  59%|█████▉    | 10088/16971 [00:03<00:02, 2877.21curve/s]

Denoising [sym4]:  61%|██████    | 10393/16971 [00:03<00:02, 2927.09curve/s]

Denoising [sym4]:  63%|██████▎   | 10689/16971 [00:03<00:02, 2935.51curve/s]

Denoising [sym4]:  65%|██████▍   | 10983/16971 [00:03<00:02, 2871.98curve/s]

Denoising [sym4]:  67%|██████▋   | 11290/16971 [00:03<00:01, 2928.04curve/s]

Denoising [sym4]:  68%|██████▊   | 11610/16971 [00:03<00:01, 3008.10curve/s]

Denoising [sym4]:  70%|███████   | 11929/16971 [00:04<00:01, 3060.41curve/s]

Denoising [sym4]:  72%|███████▏  | 12236/16971 [00:04<00:01, 3058.32curve/s]

Denoising [sym4]:  74%|███████▍  | 12558/16971 [00:04<00:01, 3104.96curve/s]

Denoising [sym4]:  76%|███████▌  | 12869/16971 [00:04<00:01, 3031.34curve/s]

Denoising [sym4]:  78%|███████▊  | 13173/16971 [00:04<00:01, 2996.09curve/s]

Denoising [sym4]:  79%|███████▉  | 13473/16971 [00:04<00:01, 2995.04curve/s]

Denoising [sym4]:  81%|████████  | 13773/16971 [00:04<00:01, 2938.52curve/s]

Denoising [sym4]:  83%|████████▎ | 14068/16971 [00:04<00:01, 2882.43curve/s]

Denoising [sym4]:  85%|████████▍ | 14357/16971 [00:04<00:00, 2854.66curve/s]

Denoising [sym4]:  86%|████████▋ | 14643/16971 [00:04<00:00, 2846.22curve/s]

Denoising [sym4]:  88%|████████▊ | 14954/16971 [00:05<00:00, 2922.05curve/s]

Denoising [sym4]:  90%|████████▉ | 15269/16971 [00:05<00:00, 2986.77curve/s]

Denoising [sym4]:  92%|█████████▏| 15595/16971 [00:05<00:00, 3066.41curve/s]

Denoising [sym4]:  94%|█████████▍| 15930/16971 [00:05<00:00, 3149.53curve/s]

Denoising [sym4]:  96%|█████████▌| 16246/16971 [00:05<00:00, 3146.61curve/s]

Denoising [sym4]:  98%|█████████▊| 16561/16971 [00:05<00:00, 2998.14curve/s]

Denoising [sym4]:  99%|█████████▉| 16863/16971 [00:05<00:00, 2911.51curve/s]

Denoising [sym4]: 100%|██████████| 16971/16971 [00:05<00:00, 2965.51curve/s]

  Wavelet sym4: SNR=10.6dB  TV=0.021  corr=0.9363

Denoising [sym6]:   0%|          | 0/16971 [00:00<?, ?curve/s]

Denoising [sym6]:   2%|▏         | 295/16971 [00:00<00:05, 2942.85curve/s]

Denoising [sym6]:   4%|▎         | 626/16971 [00:00<00:05, 3157.00curve/s]

Denoising [sym6]:   6%|▌         | 954/16971 [00:00<00:04, 3211.79curve/s]

Denoising [sym6]:   8%|▊         | 1276/16971 [00:00<00:04, 3173.70curve/s]

Denoising [sym6]:   9%|▉         | 1607/16971 [00:00<00:04, 3222.15curve/s]

Denoising [sym6]:  11%|█▏        | 1933/16971 [00:00<00:04, 3231.92curve/s]

Denoising [sym6]:  13%|█▎        | 2257/16971 [00:00<00:04, 3182.61curve/s]

Denoising [sym6]:  15%|█▌        | 2600/16971 [00:00<00:04, 3257.80curve/s]

Denoising [sym6]:  17%|█▋        | 2926/16971 [00:00<00:04, 3191.78curve/s]

Denoising [sym6]:  19%|█▉        | 3246/16971 [00:01<00:04, 3147.67curve/s]

Denoising [sym6]:  21%|██        | 3562/16971 [00:01<00:04, 3100.21curve/s]

Denoising [sym6]:  23%|██▎       | 3873/16971 [00:01<00:04, 3006.94curve/s]

Denoising [sym6]:  25%|██▍       | 4175/16971 [00:01<00:04, 2882.02curve/s]

Denoising [sym6]:  26%|██▋       | 4477/16971 [00:01<00:04, 2917.33curve/s]

Denoising [sym6]:  28%|██▊       | 4798/16971 [00:01<00:04, 3000.30curve/s]

Denoising [sym6]:  30%|███       | 5113/16971 [00:01<00:03, 3042.40curve/s]

Denoising [sym6]:  32%|███▏      | 5459/16971 [00:01<00:03, 3163.25curve/s]

Denoising [sym6]:  34%|███▍      | 5787/16971 [00:01<00:03, 3195.26curve/s]

Denoising [sym6]:  36%|███▌      | 6108/16971 [00:01<00:03, 3165.28curve/s]

Denoising [sym6]:  38%|███▊      | 6426/16971 [00:02<00:03, 3122.51curve/s]

Denoising [sym6]:  40%|███▉      | 6739/16971 [00:02<00:03, 2958.68curve/s]

Denoising [sym6]:  42%|████▏     | 7052/16971 [00:02<00:03, 3005.60curve/s]

Denoising [sym6]:  44%|████▎     | 7388/16971 [00:02<00:03, 3106.63curve/s]

Denoising [sym6]:  45%|████▌     | 7721/16971 [00:02<00:02, 3171.63curve/s]

Denoising [sym6]:  47%|████▋     | 8040/16971 [00:02<00:02, 3104.68curve/s]

Denoising [sym6]:  49%|████▉     | 8352/16971 [00:02<00:02, 3048.40curve/s]

Denoising [sym6]:  51%|█████     | 8688/16971 [00:02<00:02, 3136.18curve/s]

Denoising [sym6]:  53%|█████▎    | 9003/16971 [00:02<00:02, 3131.14curve/s]

Denoising [sym6]:  55%|█████▍    | 9318/16971 [00:02<00:02, 3136.50curve/s]

Denoising [sym6]:  57%|█████▋    | 9651/16971 [00:03<00:02, 3191.80curve/s]

Denoising [sym6]:  59%|█████▉    | 9983/16971 [00:03<00:02, 3228.75curve/s]

Denoising [sym6]:  61%|██████    | 10307/16971 [00:03<00:02, 3072.83curve/s]

Denoising [sym6]:  63%|██████▎   | 10617/16971 [00:03<00:02, 3047.66curve/s]

Denoising [sym6]:  64%|██████▍   | 10945/16971 [00:03<00:01, 3112.80curve/s]

Denoising [sym6]:  66%|██████▋   | 11258/16971 [00:03<00:01, 3092.00curve/s]

Denoising [sym6]:  68%|██████▊   | 11568/16971 [00:03<00:01, 3078.96curve/s]

Denoising [sym6]:  70%|███████   | 11886/16971 [00:03<00:01, 3107.39curve/s]

Denoising [sym6]:  72%|███████▏  | 12198/16971 [00:03<00:01, 3040.15curve/s]

Denoising [sym6]:  74%|███████▍  | 12530/16971 [00:04<00:01, 3120.29curve/s]

Denoising [sym6]:  76%|███████▌  | 12848/16971 [00:04<00:01, 3136.29curve/s]

Denoising [sym6]:  78%|███████▊  | 13163/16971 [00:04<00:01, 3048.11curve/s]

Denoising [sym6]:  79%|███████▉  | 13471/16971 [00:04<00:01, 3055.53curve/s]

Denoising [sym6]:  81%|████████▏ | 13823/16971 [00:04<00:00, 3189.27curve/s]

Denoising [sym6]:  83%|████████▎ | 14143/16971 [00:04<00:00, 3181.15curve/s]

Denoising [sym6]:  85%|████████▌ | 14464/16971 [00:04<00:00, 3187.12curve/s]

Denoising [sym6]:  87%|████████▋ | 14784/16971 [00:04<00:00, 3141.78curve/s]

Denoising [sym6]:  89%|████████▉ | 15099/16971 [00:04<00:00, 3143.40curve/s]

Denoising [sym6]:  91%|█████████ | 15433/16971 [00:04<00:00, 3201.47curve/s]

Denoising [sym6]:  93%|█████████▎| 15768/16971 [00:05<00:00, 3243.19curve/s]

Denoising [sym6]:  95%|█████████▍| 16093/16971 [00:05<00:00, 3097.74curve/s]

Denoising [sym6]:  97%|█████████▋| 16405/16971 [00:05<00:00, 3095.03curve/s]

Denoising [sym6]:  99%|█████████▊| 16719/16971 [00:05<00:00, 3105.74curve/s]

Denoising [sym6]: 100%|██████████| 16971/16971 [00:05<00:00, 3114.15curve/s]

  Wavelet sym6: SNR=10.9dB  TV=0.023  corr=0.9396

  Wavelet sym8: (already in WAVELETS)  SNR=11.3dB

D20260827_E00_C00_F4500KHz_U_DDM_01_final_final  (T=869)

Denoising [sym4]:   0%|          | 0/16381 [00:00<?, ?curve/s]

Denoising [sym4]:   2%|▏         | 366/16381 [00:00<00:04, 3654.25curve/s]

Denoising [sym4]:   4%|▍         | 732/16381 [00:00<00:04, 3458.44curve/s]

Denoising [sym4]:   7%|▋         | 1079/16381 [00:00<00:04, 3417.25curve/s]

Denoising [sym4]:   9%|▊         | 1422/16381 [00:00<00:04, 3421.32curve/s]

Denoising [sym4]:  11%|█         | 1765/16381 [00:00<00:04, 3307.04curve/s]

Denoising [sym4]:  13%|█▎        | 2117/16381 [00:00<00:04, 3375.04curve/s]

Denoising [sym4]:  15%|█▌        | 2462/16381 [00:00<00:04, 3398.85curve/s]

Denoising [sym4]:  17%|█▋        | 2830/16381 [00:00<00:03, 3486.71curve/s]

Denoising [sym4]:  19%|█▉        | 3186/16381 [00:00<00:03, 3507.06curve/s]

Denoising [sym4]:  22%|██▏       | 3538/16381 [00:01<00:03, 3500.00curve/s]

Denoising [sym4]:  24%|██▎       | 3889/16381 [00:01<00:03, 3441.56curve/s]

Denoising [sym4]:  26%|██▌       | 4234/16381 [00:01<00:03, 3411.35curve/s]

Denoising [sym4]:  28%|██▊       | 4576/16381 [00:01<00:03, 3259.24curve/s]

Denoising [sym4]:  30%|██▉       | 4908/16381 [00:01<00:03, 3274.73curve/s]

Denoising [sym4]:  32%|███▏      | 5265/16381 [00:01<00:03, 3360.42curve/s]

Denoising [sym4]:  34%|███▍      | 5603/16381 [00:01<00:03, 3330.51curve/s]

Denoising [sym4]:  36%|███▋      | 5944/16381 [00:01<00:03, 3353.09curve/s]

Denoising [sym4]:  38%|███▊      | 6282/16381 [00:01<00:03, 3358.89curve/s]

Denoising [sym4]:  40%|████      | 6619/16381 [00:01<00:03, 3229.73curve/s]

Denoising [sym4]:  43%|████▎     | 6978/16381 [00:02<00:02, 3333.52curve/s]

Denoising [sym4]:  45%|████▍     | 7323/16381 [00:02<00:02, 3367.14curve/s]

Denoising [sym4]:  47%|████▋     | 7661/16381 [00:02<00:02, 3274.78curve/s]

Denoising [sym4]:  49%|████▉     | 8022/16381 [00:02<00:02, 3371.55curve/s]

Denoising [sym4]:  51%|█████     | 8361/16381 [00:02<00:02, 3341.43curve/s]

Denoising [sym4]:  53%|█████▎    | 8700/16381 [00:02<00:02, 3352.95curve/s]

Denoising [sym4]:  55%|█████▌    | 9036/16381 [00:02<00:02, 3344.93curve/s]

Denoising [sym4]:  57%|█████▋    | 9371/16381 [00:02<00:02, 3336.75curve/s]

Denoising [sym4]:  59%|█████▉    | 9705/16381 [00:02<00:02, 3199.13curve/s]

Denoising [sym4]:  61%|██████    | 10027/16381 [00:03<00:02, 3123.05curve/s]

Denoising [sym4]:  63%|██████▎   | 10377/16381 [00:03<00:01, 3230.18curve/s]

Denoising [sym4]:  65%|██████▌   | 10702/16381 [00:03<00:01, 3199.84curve/s]

Denoising [sym4]:  67%|██████▋   | 11038/16381 [00:03<00:01, 3244.99curve/s]

Denoising [sym4]:  69%|██████▉   | 11364/16381 [00:03<00:01, 3191.88curve/s]

Denoising [sym4]:  71%|███████▏  | 11712/16381 [00:03<00:01, 3273.41curve/s]

Denoising [sym4]:  74%|███████▎  | 12058/16381 [00:03<00:01, 3325.57curve/s]

Denoising [sym4]:  76%|███████▌  | 12393/16381 [00:03<00:01, 3330.69curve/s]

Denoising [sym4]:  78%|███████▊  | 12727/16381 [00:03<00:01, 3292.30curve/s]

Denoising [sym4]:  80%|███████▉  | 13057/16381 [00:03<00:01, 3272.17curve/s]

Denoising [sym4]:  82%|████████▏ | 13385/16381 [00:04<00:00, 3237.77curve/s]

Denoising [sym4]:  84%|████████▎ | 13713/16381 [00:04<00:00, 3248.39curve/s]

Denoising [sym4]:  86%|████████▌ | 14073/16381 [00:04<00:00, 3350.63curve/s]

Denoising [sym4]:  88%|████████▊ | 14409/16381 [00:04<00:00, 3300.14curve/s]

Denoising [sym4]:  90%|█████████ | 14746/16381 [00:04<00:00, 3315.58curve/s]

Denoising [sym4]:  92%|█████████▏| 15108/16381 [00:04<00:00, 3404.50curve/s]

Denoising [sym4]:  94%|█████████▍| 15449/16381 [00:04<00:00, 3367.78curve/s]

Denoising [sym4]:  96%|█████████▋| 15787/16381 [00:04<00:00, 3325.49curve/s]

Denoising [sym4]:  99%|█████████▊| 16137/16381 [00:04<00:00, 3374.28curve/s]

Denoising [sym4]: 100%|██████████| 16381/16381 [00:04<00:00, 3332.22curve/s]

  Wavelet sym4: SNR=15.0dB  TV=0.029  corr=0.9809

Denoising [sym6]:   0%|          | 0/16381 [00:00<?, ?curve/s]

Denoising [sym6]:   2%|▏         | 333/16381 [00:00<00:04, 3327.27curve/s]

Denoising [sym6]:   4%|▍         | 666/16381 [00:00<00:04, 3313.23curve/s]

Denoising [sym6]:   6%|▌         | 998/16381 [00:00<00:04, 3162.70curve/s]

Denoising [sym6]:   8%|▊         | 1316/16381 [00:00<00:04, 3158.37curve/s]

Denoising [sym6]:  10%|▉         | 1633/16381 [00:00<00:04, 3118.29curve/s]

Denoising [sym6]:  12%|█▏        | 1987/16381 [00:00<00:04, 3258.14curve/s]

Denoising [sym6]:  14%|█▍        | 2334/16381 [00:00<00:04, 3323.71curve/s]

Denoising [sym6]:  16%|█▋        | 2667/16381 [00:00<00:04, 3253.28curve/s]

Denoising [sym6]:  18%|█▊        | 2993/16381 [00:00<00:04, 3188.15curve/s]

Denoising [sym6]:  20%|██        | 3313/16381 [00:01<00:04, 3177.92curve/s]

Denoising [sym6]:  22%|██▏       | 3642/16381 [00:01<00:03, 3209.59curve/s]

Denoising [sym6]:  24%|██▍       | 3973/16381 [00:01<00:03, 3238.61curve/s]

Denoising [sym6]:  26%|██▋       | 4310/16381 [00:01<00:03, 3277.50curve/s]

Denoising [sym6]:  28%|██▊       | 4644/16381 [00:01<00:03, 3295.22curve/s]

Denoising [sym6]:  30%|███       | 4974/16381 [00:01<00:03, 3209.57curve/s]

Denoising [sym6]:  32%|███▏      | 5296/16381 [00:01<00:03, 3194.04curve/s]

Denoising [sym6]:  34%|███▍      | 5616/16381 [00:01<00:03, 3182.86curve/s]

Denoising [sym6]:  36%|███▋      | 5946/16381 [00:01<00:03, 3215.29curve/s]

Denoising [sym6]:  38%|███▊      | 6268/16381 [00:01<00:03, 3159.63curve/s]

Denoising [sym6]:  40%|████      | 6585/16381 [00:02<00:03, 3090.29curve/s]

Denoising [sym6]:  42%|████▏     | 6906/16381 [00:02<00:03, 3123.64curve/s]

Denoising [sym6]:  44%|████▍     | 7237/16381 [00:02<00:02, 3174.92curve/s]

Denoising [sym6]:  46%|████▌     | 7555/16381 [00:02<00:02, 3134.35curve/s]

Denoising [sym6]:  48%|████▊     | 7905/16381 [00:02<00:02, 3239.71curve/s]

Denoising [sym6]:  50%|█████     | 8241/16381 [00:02<00:02, 3273.80curve/s]

Denoising [sym6]:  52%|█████▏    | 8569/16381 [00:02<00:02, 3192.61curve/s]

Denoising [sym6]:  54%|█████▍    | 8912/16381 [00:02<00:02, 3257.97curve/s]

Denoising [sym6]:  56%|█████▋    | 9239/16381 [00:02<00:02, 3153.05curve/s]

Denoising [sym6]:  58%|█████▊    | 9562/16381 [00:02<00:02, 3172.98curve/s]

Denoising [sym6]:  60%|██████    | 9881/16381 [00:03<00:02, 3121.76curve/s]

Denoising [sym6]:  62%|██████▏   | 10197/16381 [00:03<00:01, 3130.96curve/s]

Denoising [sym6]:  64%|██████▍   | 10511/16381 [00:03<00:01, 3057.12curve/s]

Denoising [sym6]:  66%|██████▌   | 10828/16381 [00:03<00:01, 3089.71curve/s]

Denoising [sym6]:  68%|██████▊   | 11159/16381 [00:03<00:01, 3153.40curve/s]

Denoising [sym6]:  70%|███████   | 11475/16381 [00:03<00:01, 3127.81curve/s]

Denoising [sym6]:  72%|███████▏  | 11803/16381 [00:03<00:01, 3170.64curve/s]

Denoising [sym6]:  74%|███████▍  | 12128/16381 [00:03<00:01, 3193.69curve/s]

Denoising [sym6]:  76%|███████▌  | 12448/16381 [00:03<00:01, 3190.84curve/s]

Denoising [sym6]:  78%|███████▊  | 12768/16381 [00:04<00:01, 3098.49curve/s]

Denoising [sym6]:  80%|███████▉  | 13087/16381 [00:04<00:01, 3124.51curve/s]

Denoising [sym6]:  82%|████████▏ | 13400/16381 [00:04<00:00, 3113.99curve/s]

Denoising [sym6]:  84%|████████▍ | 13725/16381 [00:04<00:00, 3151.74curve/s]

Denoising [sym6]:  86%|████████▌ | 14061/16381 [00:04<00:00, 3212.91curve/s]

Denoising [sym6]:  88%|████████▊ | 14383/16381 [00:04<00:00, 3199.90curve/s]

Denoising [sym6]:  90%|████████▉ | 14726/16381 [00:04<00:00, 3266.49curve/s]

Denoising [sym6]:  92%|█████████▏| 15071/16381 [00:04<00:00, 3319.99curve/s]

Denoising [sym6]:  94%|█████████▍| 15404/16381 [00:04<00:00, 3314.98curve/s]

Denoising [sym6]:  96%|█████████▌| 15736/16381 [00:04<00:00, 3284.73curve/s]

Denoising [sym6]:  98%|█████████▊| 16075/16381 [00:05<00:00, 3314.42curve/s]

Denoising [sym6]: 100%|██████████| 16381/16381 [00:05<00:00, 3196.18curve/s]

  Wavelet sym6: SNR=15.0dB  TV=0.028  corr=0.9809

  Wavelet sym8: (already in WAVELETS)  SNR=15.3dB

D20260827_E00_C00_F4500KHz_U_DDM_02_final_final  (T=905)

Denoising [sym4]:   0%|          | 0/16638 [00:00<?, ?curve/s]

Denoising [sym4]:   2%|▏         | 342/16638 [00:00<00:04, 3411.54curve/s]

Denoising [sym4]:   4%|▍         | 684/16638 [00:00<00:05, 2922.98curve/s]

Denoising [sym4]:   6%|▌         | 981/16638 [00:00<00:05, 2912.67curve/s]

Denoising [sym4]:   8%|▊         | 1275/16638 [00:00<00:05, 2861.81curve/s]

Denoising [sym4]:   9%|▉         | 1571/16638 [00:00<00:05, 2894.63curve/s]

Denoising [sym4]:  11%|█▏        | 1878/16638 [00:00<00:05, 2949.94curve/s]

Denoising [sym4]:  13%|█▎        | 2191/16638 [00:00<00:04, 3004.82curve/s]

Denoising [sym4]:  15%|█▍        | 2493/16638 [00:00<00:04, 2911.21curve/s]

Denoising [sym4]:  17%|█▋        | 2786/16638 [00:00<00:04, 2903.25curve/s]

Denoising [sym4]:  18%|█▊        | 3077/16638 [00:01<00:04, 2895.98curve/s]

Denoising [sym4]:  20%|██        | 3394/16638 [00:01<00:04, 2977.11curve/s]

Denoising [sym4]:  22%|██▏       | 3715/16638 [00:01<00:04, 3044.68curve/s]

Denoising [sym4]:  24%|██▍       | 4030/16638 [00:01<00:04, 3075.18curve/s]

Denoising [sym4]:  26%|██▌       | 4353/16638 [00:01<00:03, 3121.32curve/s]

Denoising [sym4]:  28%|██▊       | 4666/16638 [00:01<00:03, 3080.89curve/s]

Denoising [sym4]:  30%|██▉       | 4975/16638 [00:01<00:03, 2988.57curve/s]

Denoising [sym4]:  32%|███▏      | 5275/16638 [00:01<00:03, 2971.96curve/s]

Denoising [sym4]:  34%|███▎      | 5574/16638 [00:01<00:03, 2976.41curve/s]

Denoising [sym4]:  35%|███▌      | 5872/16638 [00:01<00:03, 2958.06curve/s]

Denoising [sym4]:  37%|███▋      | 6169/16638 [00:02<00:03, 2928.37curve/s]

Denoising [sym4]:  39%|███▉      | 6472/16638 [00:02<00:03, 2956.43curve/s]

Denoising [sym4]:  41%|████      | 6768/16638 [00:02<00:03, 2911.92curve/s]

Denoising [sym4]:  42%|████▏     | 7071/16638 [00:02<00:03, 2945.37curve/s]

Denoising [sym4]:  44%|████▍     | 7366/16638 [00:02<00:03, 2942.99curve/s]

Denoising [sym4]:  46%|████▌     | 7669/16638 [00:02<00:03, 2966.97curve/s]

Denoising [sym4]:  48%|████▊     | 7972/16638 [00:02<00:02, 2982.54curve/s]

Denoising [sym4]:  50%|████▉     | 8271/16638 [00:02<00:02, 2926.83curve/s]

Denoising [sym4]:  52%|█████▏    | 8580/16638 [00:02<00:02, 2972.75curve/s]

Denoising [sym4]:  53%|█████▎    | 8891/16638 [00:02<00:02, 3010.86curve/s]

Denoising [sym4]:  55%|█████▌    | 9193/16638 [00:03<00:02, 2979.23curve/s]

Denoising [sym4]:  57%|█████▋    | 9492/16638 [00:03<00:02, 2906.00curve/s]

Denoising [sym4]:  59%|█████▉    | 9802/16638 [00:03<00:02, 2962.04curve/s]

Denoising [sym4]:  61%|██████    | 10099/16638 [00:03<00:02, 2949.12curve/s]

Denoising [sym4]:  63%|██████▎   | 10400/16638 [00:03<00:02, 2967.00curve/s]

Denoising [sym4]:  64%|██████▍   | 10713/16638 [00:03<00:01, 3013.32curve/s]

Denoising [sym4]:  66%|██████▌   | 11015/16638 [00:03<00:01, 2958.61curve/s]

Denoising [sym4]:  68%|██████▊   | 11312/16638 [00:03<00:01, 2904.81curve/s]

Denoising [sym4]:  70%|██████▉   | 11603/16638 [00:03<00:01, 2866.91curve/s]

Denoising [sym4]:  71%|███████▏  | 11891/16638 [00:04<00:01, 2866.97curve/s]

Denoising [sym4]:  73%|███████▎  | 12200/16638 [00:04<00:01, 2931.36curve/s]

Denoising [sym4]:  75%|███████▌  | 12494/16638 [00:04<00:01, 2900.27curve/s]

Denoising [sym4]:  77%|███████▋  | 12800/16638 [00:04<00:01, 2945.99curve/s]

Denoising [sym4]:  79%|███████▉  | 13109/16638 [00:04<00:01, 2988.42curve/s]

Denoising [sym4]:  81%|████████  | 13418/16638 [00:04<00:01, 3016.50curve/s]

Denoising [sym4]:  83%|████████▎ | 13738/16638 [00:04<00:00, 3069.08curve/s]

Denoising [sym4]:  84%|████████▍ | 14058/16638 [00:04<00:00, 3107.72curve/s]

Denoising [sym4]:  86%|████████▋ | 14388/16638 [00:04<00:00, 3164.19curve/s]

Denoising [sym4]:  88%|████████▊ | 14705/16638 [00:04<00:00, 3082.32curve/s]

Denoising [sym4]:  90%|█████████ | 15014/16638 [00:05<00:00, 3060.76curve/s]

Denoising [sym4]:  92%|█████████▏| 15321/16638 [00:05<00:00, 3056.91curve/s]

Denoising [sym4]:  94%|█████████▍| 15627/16638 [00:05<00:00, 3017.78curve/s]

Denoising [sym4]:  96%|█████████▌| 15938/16638 [00:05<00:00, 3044.07curve/s]

Denoising [sym4]:  98%|█████████▊| 16262/16638 [00:05<00:00, 3101.27curve/s]

Denoising [sym4]: 100%|█████████▉| 16573/16638 [00:05<00:00, 3079.84curve/s]

Denoising [sym4]: 100%|██████████| 16638/16638 [00:05<00:00, 2987.59curve/s]

  Wavelet sym4: SNR=16.5dB  TV=0.031  corr=0.9838

Denoising [sym6]:   0%|          | 0/16638 [00:00<?, ?curve/s]

Denoising [sym6]:   2%|▏         | 271/16638 [00:00<00:06, 2706.64curve/s]

Denoising [sym6]:   4%|▎         | 612/16638 [00:00<00:05, 3117.91curve/s]

Denoising [sym6]:   6%|▌         | 945/16638 [00:00<00:04, 3211.34curve/s]

Denoising [sym6]:   8%|▊         | 1267/16638 [00:00<00:04, 3210.53curve/s]

Denoising [sym6]:  10%|▉         | 1592/16638 [00:00<00:04, 3224.39curve/s]

Denoising [sym6]:  12%|█▏        | 1921/16638 [00:00<00:04, 3244.63curve/s]

Denoising [sym6]:  14%|█▎        | 2273/16638 [00:00<00:04, 3332.93curve/s]

Denoising [sym6]:  16%|█▌        | 2607/16638 [00:00<00:04, 3328.29curve/s]

Denoising [sym6]:  18%|█▊        | 2959/16638 [00:00<00:04, 3386.81curve/s]

Denoising [sym6]:  20%|█▉        | 3304/16638 [00:01<00:03, 3404.86curve/s]

Denoising [sym6]:  22%|██▏       | 3645/16638 [00:01<00:03, 3332.58curve/s]

Denoising [sym6]:  24%|██▍       | 3979/16638 [00:01<00:03, 3207.64curve/s]

Denoising [sym6]:  26%|██▌       | 4301/16638 [00:01<00:03, 3142.28curve/s]

Denoising [sym6]:  28%|██▊       | 4633/16638 [00:01<00:03, 3192.75curve/s]

Denoising [sym6]:  30%|██▉       | 4954/16638 [00:01<00:03, 3160.11curve/s]

Denoising [sym6]:  32%|███▏      | 5271/16638 [00:01<00:03, 3146.16curve/s]

Denoising [sym6]:  34%|███▍      | 5628/16638 [00:01<00:03, 3268.88curve/s]

Denoising [sym6]:  36%|███▌      | 5956/16638 [00:01<00:03, 3211.39curve/s]

Denoising [sym6]:  38%|███▊      | 6297/16638 [00:01<00:03, 3267.00curve/s]

Denoising [sym6]:  40%|███▉      | 6630/16638 [00:02<00:03, 3284.37curve/s]

Denoising [sym6]:  42%|████▏     | 6975/16638 [00:02<00:02, 3333.35curve/s]

Denoising [sym6]:  44%|████▍     | 7309/16638 [00:02<00:02, 3228.82curve/s]

Denoising [sym6]:  46%|████▌     | 7633/16638 [00:02<00:02, 3134.34curve/s]

Denoising [sym6]:  48%|████▊     | 7948/16638 [00:02<00:02, 3082.13curve/s]

Denoising [sym6]:  50%|████▉     | 8257/16638 [00:02<00:02, 3006.39curve/s]

Denoising [sym6]:  52%|█████▏    | 8573/16638 [00:02<00:02, 3048.86curve/s]

Denoising [sym6]:  53%|█████▎    | 8889/16638 [00:02<00:02, 3078.57curve/s]

Denoising [sym6]:  55%|█████▌    | 9225/16638 [00:02<00:02, 3158.87curve/s]

Denoising [sym6]:  57%|█████▋    | 9546/16638 [00:02<00:02, 3172.47curve/s]

Denoising [sym6]:  59%|█████▉    | 9895/16638 [00:03<00:02, 3265.80curve/s]

Denoising [sym6]:  61%|██████▏   | 10222/16638 [00:03<00:01, 3250.81curve/s]

Denoising [sym6]:  63%|██████▎   | 10548/16638 [00:03<00:01, 3165.86curve/s]

Denoising [sym6]:  65%|██████▌   | 10890/16638 [00:03<00:01, 3237.91curve/s]

Denoising [sym6]:  67%|██████▋   | 11215/16638 [00:03<00:01, 3231.79curve/s]

Denoising [sym6]:  69%|██████▉   | 11539/16638 [00:03<00:01, 3160.93curve/s]

Denoising [sym6]:  71%|███████▏  | 11861/16638 [00:03<00:01, 3178.16curve/s]

Denoising [sym6]:  73%|███████▎  | 12180/16638 [00:03<00:01, 3148.28curve/s]

Denoising [sym6]:  75%|███████▌  | 12515/16638 [00:03<00:01, 3207.15curve/s]

Denoising [sym6]:  77%|███████▋  | 12838/16638 [00:04<00:01, 3212.79curve/s]

Denoising [sym6]:  79%|███████▉  | 13160/16638 [00:04<00:01, 3192.84curve/s]

Denoising [sym6]:  81%|████████  | 13480/16638 [00:04<00:01, 3143.96curve/s]

Denoising [sym6]:  83%|████████▎ | 13805/16638 [00:04<00:00, 3173.43curve/s]

Denoising [sym6]:  85%|████████▍ | 14123/16638 [00:04<00:00, 3152.64curve/s]

Denoising [sym6]:  87%|████████▋ | 14439/16638 [00:04<00:00, 3133.73curve/s]

Denoising [sym6]:  89%|████████▊ | 14753/16638 [00:04<00:00, 3121.29curve/s]

Denoising [sym6]:  91%|█████████ | 15066/16638 [00:04<00:00, 3059.82curve/s]

Denoising [sym6]:  92%|█████████▏| 15389/16638 [00:04<00:00, 3108.73curve/s]

Denoising [sym6]:  95%|█████████▍| 15724/16638 [00:04<00:00, 3177.79curve/s]

Denoising [sym6]:  96%|█████████▋| 16052/16638 [00:05<00:00, 3206.06curve/s]

Denoising [sym6]:  98%|█████████▊| 16373/16638 [00:05<00:00, 3198.14curve/s]

Denoising [sym6]: 100%|██████████| 16638/16638 [00:05<00:00, 3190.11curve/s]

  Wavelet sym6: SNR=16.8dB  TV=0.033  corr=0.9846

  Wavelet sym8: (already in WAVELETS)  SNR=17.0dB

D20260827_E00_C00_F4500KHz_U_DDM_03_final_final  (T=560)

Denoising [sym4]:   0%|          | 0/16754 [00:00<?, ?curve/s]

Denoising [sym4]:   2%|▏         | 337/16754 [00:00<00:04, 3365.09curve/s]

Denoising [sym4]:   4%|▍         | 683/16754 [00:00<00:04, 3419.74curve/s]

Denoising [sym4]:   6%|▋         | 1055/16754 [00:00<00:04, 3553.67curve/s]

Denoising [sym4]:   9%|▊         | 1428/16754 [00:00<00:04, 3621.50curve/s]

Denoising [sym4]:  11%|█         | 1791/16754 [00:00<00:04, 3337.01curve/s]

Denoising [sym4]:  13%|█▎        | 2136/16754 [00:00<00:04, 3372.42curve/s]

Denoising [sym4]:  15%|█▍        | 2483/16754 [00:00<00:04, 3401.24curve/s]

Denoising [sym4]:  17%|█▋        | 2836/16754 [00:00<00:04, 3439.59curve/s]

Denoising [sym4]:  19%|█▉        | 3182/16754 [00:00<00:04, 3381.68curve/s]

Denoising [sym4]:  21%|██        | 3522/16754 [00:01<00:03, 3352.35curve/s]

Denoising [sym4]:  23%|██▎       | 3880/16754 [00:01<00:03, 3418.02curve/s]

Denoising [sym4]:  25%|██▌       | 4223/16754 [00:01<00:03, 3272.56curve/s]

Denoising [sym4]:  27%|██▋       | 4552/16754 [00:01<00:03, 3245.67curve/s]

Denoising [sym4]:  29%|██▉       | 4878/16754 [00:01<00:03, 3174.98curve/s]

Denoising [sym4]:  31%|███       | 5235/16754 [00:01<00:03, 3288.74curve/s]

Denoising [sym4]:  33%|███▎      | 5565/16754 [00:01<00:03, 3286.23curve/s]

Denoising [sym4]:  35%|███▌      | 5895/16754 [00:01<00:03, 3231.21curve/s]

Denoising [sym4]:  37%|███▋      | 6234/16754 [00:01<00:03, 3277.24curve/s]

Denoising [sym4]:  39%|███▉      | 6563/16754 [00:01<00:03, 3206.14curve/s]

Denoising [sym4]:  41%|████      | 6899/16754 [00:02<00:03, 3249.96curve/s]

Denoising [sym4]:  43%|████▎     | 7233/16754 [00:02<00:02, 3274.10curve/s]

Denoising [sym4]:  45%|████▌     | 7583/16754 [00:02<00:02, 3338.04curve/s]

Denoising [sym4]:  47%|████▋     | 7918/16754 [00:02<00:02, 3338.66curve/s]

Denoising [sym4]:  49%|████▉     | 8253/16754 [00:02<00:02, 3273.79curve/s]

Denoising [sym4]:  51%|█████▏    | 8592/16754 [00:02<00:02, 3305.98curve/s]

Denoising [sym4]:  53%|█████▎    | 8934/16754 [00:02<00:02, 3339.59curve/s]

Denoising [sym4]:  56%|█████▌    | 9304/16754 [00:02<00:02, 3446.44curve/s]

Denoising [sym4]:  58%|█████▊    | 9649/16754 [00:02<00:02, 3397.26curve/s]

Denoising [sym4]:  60%|█████▉    | 10015/16754 [00:02<00:01, 3474.27curve/s]

Denoising [sym4]:  62%|██████▏   | 10363/16754 [00:03<00:01, 3441.18curve/s]

Denoising [sym4]:  64%|██████▍   | 10708/16754 [00:03<00:01, 3373.81curve/s]

Denoising [sym4]:  66%|██████▌   | 11046/16754 [00:03<00:01, 3351.57curve/s]

Denoising [sym4]:  68%|██████▊   | 11404/16754 [00:03<00:01, 3416.60curve/s]

Denoising [sym4]:  70%|███████   | 11746/16754 [00:03<00:01, 3378.71curve/s]

Denoising [sym4]:  72%|███████▏  | 12109/16754 [00:03<00:01, 3449.70curve/s]

Denoising [sym4]:  74%|███████▍  | 12455/16754 [00:03<00:01, 3388.44curve/s]

Denoising [sym4]:  76%|███████▋  | 12810/16754 [00:03<00:01, 3431.67curve/s]

Denoising [sym4]:  79%|███████▊  | 13164/16754 [00:03<00:01, 3459.84curve/s]

Denoising [sym4]:  81%|████████  | 13511/16754 [00:04<00:00, 3257.71curve/s]

Denoising [sym4]:  83%|████████▎ | 13840/16754 [00:04<00:00, 3261.61curve/s]

Denoising [sym4]:  85%|████████▍ | 14171/16754 [00:04<00:00, 3275.20curve/s]

Denoising [sym4]:  87%|████████▋ | 14512/16754 [00:04<00:00, 3310.97curve/s]

Denoising [sym4]:  89%|████████▊ | 14847/16754 [00:04<00:00, 3319.90curve/s]

Denoising [sym4]:  91%|█████████ | 15180/16754 [00:04<00:00, 3146.89curve/s]

Denoising [sym4]:  93%|█████████▎| 15518/16754 [00:04<00:00, 3212.94curve/s]

Denoising [sym4]:  95%|█████████▍| 15851/16754 [00:04<00:00, 3244.77curve/s]

Denoising [sym4]:  97%|█████████▋| 16203/16754 [00:04<00:00, 3325.30curve/s]

Denoising [sym4]:  99%|█████████▉| 16567/16754 [00:04<00:00, 3418.00curve/s]

Denoising [sym4]: 100%|██████████| 16754/16754 [00:05<00:00, 3346.79curve/s]

  Wavelet sym4: SNR=12.5dB  TV=0.033  corr=0.9540

Denoising [sym6]:   0%|          | 0/16754 [00:00<?, ?curve/s]

Denoising [sym6]:   2%|▏         | 352/16754 [00:00<00:04, 3514.02curve/s]

Denoising [sym6]:   4%|▍         | 721/16754 [00:00<00:04, 3612.77curve/s]

Denoising [sym6]:   6%|▋         | 1083/16754 [00:00<00:04, 3535.32curve/s]

Denoising [sym6]:   9%|▊         | 1444/16754 [00:00<00:04, 3561.62curve/s]

Denoising [sym6]:  11%|█         | 1831/16754 [00:00<00:04, 3671.19curve/s]

Denoising [sym6]:  13%|█▎        | 2210/16754 [00:00<00:03, 3708.09curve/s]

Denoising [sym6]:  15%|█▌        | 2581/16754 [00:00<00:03, 3578.46curve/s]

Denoising [sym6]:  18%|█▊        | 2940/16754 [00:00<00:03, 3495.73curve/s]

Denoising [sym6]:  20%|█▉        | 3310/16754 [00:00<00:03, 3556.88curve/s]

Denoising [sym6]:  22%|██▏       | 3667/16754 [00:01<00:03, 3463.65curve/s]

Denoising [sym6]:  24%|██▍       | 4035/16754 [00:01<00:03, 3525.38curve/s]

Denoising [sym6]:  26%|██▌       | 4397/16754 [00:01<00:03, 3552.34curve/s]

Denoising [sym6]:  28%|██▊       | 4753/16754 [00:01<00:03, 3525.66curve/s]

Denoising [sym6]:  30%|███       | 5107/16754 [00:01<00:03, 3525.84curve/s]

Denoising [sym6]:  33%|███▎      | 5507/16754 [00:01<00:03, 3665.46curve/s]

Denoising [sym6]:  35%|███▌      | 5874/16754 [00:01<00:03, 3604.85curve/s]

Denoising [sym6]:  37%|███▋      | 6235/16754 [00:01<00:02, 3553.23curve/s]

Denoising [sym6]:  39%|███▉      | 6593/16754 [00:01<00:02, 3558.13curve/s]

Denoising [sym6]:  42%|████▏     | 6959/16754 [00:01<00:02, 3586.50curve/s]

Denoising [sym6]:  44%|████▍     | 7334/16754 [00:02<00:02, 3632.87curve/s]

Denoising [sym6]:  46%|████▌     | 7698/16754 [00:02<00:02, 3570.62curve/s]

Denoising [sym6]:  48%|████▊     | 8056/16754 [00:02<00:02, 3534.89curve/s]

Denoising [sym6]:  50%|█████     | 8430/16754 [00:02<00:02, 3593.59curve/s]

Denoising [sym6]:  53%|█████▎    | 8822/16754 [00:02<00:02, 3687.76curve/s]

Denoising [sym6]:  55%|█████▍    | 9212/16754 [00:02<00:02, 3748.29curve/s]

Denoising [sym6]:  57%|█████▋    | 9588/16754 [00:02<00:01, 3718.18curve/s]

Denoising [sym6]:  59%|█████▉    | 9961/16754 [00:02<00:01, 3680.82curve/s]

Denoising [sym6]:  62%|██████▏   | 10330/16754 [00:02<00:01, 3615.58curve/s]

Denoising [sym6]:  64%|██████▍   | 10692/16754 [00:02<00:01, 3528.58curve/s]

Denoising [sym6]:  66%|██████▌   | 11054/16754 [00:03<00:01, 3552.16curve/s]

Denoising [sym6]:  68%|██████▊   | 11411/16754 [00:03<00:01, 3556.37curve/s]

Denoising [sym6]:  70%|███████   | 11767/16754 [00:03<00:01, 3473.03curve/s]

Denoising [sym6]:  72%|███████▏  | 12138/16754 [00:03<00:01, 3540.72curve/s]

Denoising [sym6]:  75%|███████▍  | 12494/16754 [00:03<00:01, 3544.27curve/s]

Denoising [sym6]:  77%|███████▋  | 12852/16754 [00:03<00:01, 3551.54curve/s]

Denoising [sym6]:  79%|███████▉  | 13208/16754 [00:03<00:01, 3520.38curve/s]

Denoising [sym6]:  81%|████████  | 13588/16754 [00:03<00:00, 3602.01curve/s]

Denoising [sym6]:  83%|████████▎ | 13949/16754 [00:03<00:00, 3564.10curve/s]

Denoising [sym6]:  85%|████████▌ | 14306/16754 [00:04<00:00, 3446.67curve/s]

Denoising [sym6]:  87%|████████▋ | 14652/16754 [00:04<00:00, 3420.95curve/s]

Denoising [sym6]:  90%|████████▉ | 15003/16754 [00:04<00:00, 3445.28curve/s]

Denoising [sym6]:  92%|█████████▏| 15351/16754 [00:04<00:00, 3455.35curve/s]

Denoising [sym6]:  94%|█████████▍| 15730/16754 [00:04<00:00, 3553.58curve/s]

Denoising [sym6]:  96%|█████████▌| 16086/16754 [00:04<00:00, 3539.30curve/s]

Denoising [sym6]:  98%|█████████▊| 16441/16754 [00:04<00:00, 3495.77curve/s]

Denoising [sym6]: 100%|██████████| 16754/16754 [00:04<00:00, 3566.72curve/s]

  Wavelet sym6: SNR=12.8dB  TV=0.037  corr=0.9575

  Wavelet sym8: (already in WAVELETS)  SNR=12.8dB

D20260827_E00_C00_F4500KHz_U_DDM_04_final_final  (T=868)

Denoising [sym4]:   0%|          | 0/16480 [00:00<?, ?curve/s]

Denoising [sym4]:   2%|▏         | 305/16480 [00:00<00:05, 3040.46curve/s]

Denoising [sym4]:   4%|▍         | 643/16480 [00:00<00:04, 3239.49curve/s]

Denoising [sym4]:   6%|▌         | 972/16480 [00:00<00:04, 3261.89curve/s]

Denoising [sym4]:   8%|▊         | 1307/16480 [00:00<00:04, 3293.48curve/s]

Denoising [sym4]:  10%|▉         | 1637/16480 [00:00<00:04, 3222.96curve/s]

Denoising [sym4]:  12%|█▏        | 1964/16480 [00:00<00:04, 3237.67curve/s]

Denoising [sym4]:  14%|█▍        | 2288/16480 [00:00<00:04, 3228.66curve/s]

Denoising [sym4]:  16%|█▌        | 2651/16480 [00:00<00:04, 3353.08curve/s]

Denoising [sym4]:  18%|█▊        | 2987/16480 [00:00<00:04, 3231.72curve/s]

Denoising [sym4]:  20%|██        | 3312/16480 [00:01<00:04, 3170.25curve/s]

Denoising [sym4]:  22%|██▏       | 3641/16480 [00:01<00:04, 3204.53curve/s]

Denoising [sym4]:  24%|██▍       | 3963/16480 [00:01<00:04, 3119.16curve/s]

Denoising [sym4]:  26%|██▌       | 4303/16480 [00:01<00:03, 3200.67curve/s]

Denoising [sym4]:  28%|██▊       | 4647/16480 [00:01<00:03, 3270.51curve/s]

Denoising [sym4]:  30%|███       | 5001/16480 [00:01<00:03, 3349.22curve/s]

Denoising [sym4]:  32%|███▏      | 5337/16480 [00:01<00:03, 3323.35curve/s]

Denoising [sym4]:  34%|███▍      | 5670/16480 [00:01<00:03, 3270.58curve/s]

Denoising [sym4]:  36%|███▋      | 5998/16480 [00:01<00:03, 3091.46curve/s]

Denoising [sym4]:  39%|███▊      | 6359/16480 [00:01<00:03, 3237.87curve/s]

Denoising [sym4]:  41%|████      | 6686/16480 [00:02<00:03, 3169.25curve/s]

Denoising [sym4]:  43%|████▎     | 7005/16480 [00:02<00:03, 3128.41curve/s]

Denoising [sym4]:  44%|████▍     | 7320/16480 [00:02<00:02, 3105.14curve/s]

Denoising [sym4]:  46%|████▋     | 7656/16480 [00:02<00:02, 3174.76curve/s]

Denoising [sym4]:  48%|████▊     | 7975/16480 [00:02<00:02, 3131.44curve/s]

Denoising [sym4]:  51%|█████     | 8323/16480 [00:02<00:02, 3232.25curve/s]

Denoising [sym4]:  52%|█████▏    | 8647/16480 [00:02<00:02, 3184.41curve/s]

Denoising [sym4]:  55%|█████▍    | 9002/16480 [00:02<00:02, 3290.90curve/s]

Denoising [sym4]:  57%|█████▋    | 9362/16480 [00:02<00:02, 3380.45curve/s]

Denoising [sym4]:  59%|█████▉    | 9701/16480 [00:02<00:02, 3347.64curve/s]

Denoising [sym4]:  61%|██████    | 10037/16480 [00:03<00:01, 3348.06curve/s]

Denoising [sym4]:  63%|██████▎   | 10373/16480 [00:03<00:01, 3329.49curve/s]

Denoising [sym4]:  65%|██████▌   | 10722/16480 [00:03<00:01, 3375.23curve/s]

Denoising [sym4]:  67%|██████▋   | 11060/16480 [00:03<00:01, 3186.29curve/s]

Denoising [sym4]:  69%|██████▉   | 11386/16480 [00:03<00:01, 3206.58curve/s]

Denoising [sym4]:  71%|███████   | 11728/16480 [00:03<00:01, 3268.39curve/s]

Denoising [sym4]:  73%|███████▎  | 12057/16480 [00:03<00:01, 3160.67curve/s]

Denoising [sym4]:  75%|███████▌  | 12385/16480 [00:03<00:01, 3193.94curve/s]

Denoising [sym4]:  77%|███████▋  | 12719/16480 [00:03<00:01, 3234.63curve/s]

Denoising [sym4]:  79%|███████▉  | 13044/16480 [00:04<00:01, 3224.22curve/s]

Denoising [sym4]:  81%|████████  | 13381/16480 [00:04<00:00, 3266.15curve/s]

Denoising [sym4]:  83%|████████▎ | 13717/16480 [00:04<00:00, 3292.35curve/s]

Denoising [sym4]:  85%|████████▌ | 14065/16480 [00:04<00:00, 3345.46curve/s]

Denoising [sym4]:  87%|████████▋ | 14402/16480 [00:04<00:00, 3349.47curve/s]

Denoising [sym4]:  89%|████████▉ | 14738/16480 [00:04<00:00, 3309.93curve/s]

Denoising [sym4]:  91%|█████████▏| 15070/16480 [00:04<00:00, 3236.17curve/s]

Denoising [sym4]:  93%|█████████▎| 15405/16480 [00:04<00:00, 3269.36curve/s]

Denoising [sym4]:  96%|█████████▌| 15754/16480 [00:04<00:00, 3332.93curve/s]

Denoising [sym4]:  98%|█████████▊| 16088/16480 [00:04<00:00, 3318.52curve/s]

Denoising [sym4]: 100%|█████████▉| 16445/16480 [00:05<00:00, 3391.23curve/s]

Denoising [sym4]: 100%|██████████| 16480/16480 [00:05<00:00, 3256.34curve/s]

  Wavelet sym4: SNR=13.0dB  TV=0.026  corr=0.9711

Denoising [sym6]:   0%|          | 0/16480 [00:00<?, ?curve/s]

Denoising [sym6]:   2%|▏         | 310/16480 [00:00<00:05, 3096.80curve/s]

Denoising [sym6]:   4%|▍         | 630/16480 [00:00<00:05, 3155.29curve/s]

Denoising [sym6]:   6%|▌         | 946/16480 [00:00<00:05, 2968.44curve/s]

Denoising [sym6]:   8%|▊         | 1245/16480 [00:00<00:05, 2918.73curve/s]

Denoising [sym6]:  10%|▉         | 1576/16480 [00:00<00:04, 3053.91curve/s]

Denoising [sym6]:  12%|█▏        | 1896/16480 [00:00<00:04, 3100.27curve/s]

Denoising [sym6]:  14%|█▎        | 2235/16480 [00:00<00:04, 3191.78curve/s]

Denoising [sym6]:  16%|█▌        | 2555/16480 [00:00<00:04, 3098.49curve/s]

Denoising [sym6]:  18%|█▊        | 2903/16480 [00:00<00:04, 3213.33curve/s]

Denoising [sym6]:  20%|█▉        | 3226/16480 [00:01<00:04, 3122.87curve/s]

Denoising [sym6]:  22%|██▏       | 3545/16480 [00:01<00:04, 3140.75curve/s]

Denoising [sym6]:  23%|██▎       | 3860/16480 [00:01<00:04, 3091.80curve/s]

Denoising [sym6]:  26%|██▌       | 4211/16480 [00:01<00:03, 3213.41curve/s]

Denoising [sym6]:  28%|██▊       | 4552/16480 [00:01<00:03, 3269.36curve/s]

Denoising [sym6]:  30%|██▉       | 4883/16480 [00:01<00:03, 3279.82curve/s]

Denoising [sym6]:  32%|███▏      | 5212/16480 [00:01<00:03, 3142.19curve/s]

Denoising [sym6]:  34%|███▎      | 5549/16480 [00:01<00:03, 3207.45curve/s]

Denoising [sym6]:  36%|███▌      | 5884/16480 [00:01<00:03, 3246.82curve/s]

Denoising [sym6]:  38%|███▊      | 6215/16480 [00:01<00:03, 3264.39curve/s]

Denoising [sym6]:  40%|███▉      | 6543/16480 [00:02<00:03, 3188.43curve/s]

Denoising [sym6]:  42%|████▏     | 6876/16480 [00:02<00:02, 3227.47curve/s]

Denoising [sym6]:  44%|████▎     | 7200/16480 [00:02<00:02, 3210.60curve/s]

Denoising [sym6]:  46%|████▌     | 7522/16480 [00:02<00:02, 3175.33curve/s]

Denoising [sym6]:  48%|████▊     | 7840/16480 [00:02<00:02, 3160.04curve/s]

Denoising [sym6]:  50%|████▉     | 8187/16480 [00:02<00:02, 3250.96curve/s]

Denoising [sym6]:  52%|█████▏    | 8513/16480 [00:02<00:02, 3225.49curve/s]

Denoising [sym6]:  54%|█████▎    | 8847/16480 [00:02<00:02, 3258.86curve/s]

Denoising [sym6]:  56%|█████▌    | 9174/16480 [00:02<00:02, 3172.72curve/s]

Denoising [sym6]:  58%|█████▊    | 9492/16480 [00:02<00:02, 3166.90curve/s]

Denoising [sym6]:  60%|█████▉    | 9810/16480 [00:03<00:02, 3106.76curve/s]

Denoising [sym6]:  62%|██████▏   | 10138/16480 [00:03<00:02, 3154.79curve/s]

Denoising [sym6]:  63%|██████▎   | 10459/16480 [00:03<00:01, 3170.11curve/s]

Denoising [sym6]:  65%|██████▌   | 10791/16480 [00:03<00:01, 3213.24curve/s]

Denoising [sym6]:  67%|██████▋   | 11113/16480 [00:03<00:01, 3167.13curve/s]

Denoising [sym6]:  70%|██████▉   | 11456/16480 [00:03<00:01, 3243.34curve/s]

Denoising [sym6]:  71%|███████▏  | 11781/16480 [00:03<00:01, 3210.47curve/s]

Denoising [sym6]:  73%|███████▎  | 12108/16480 [00:03<00:01, 3227.22curve/s]

Denoising [sym6]:  75%|███████▌  | 12441/16480 [00:03<00:01, 3255.41curve/s]

Denoising [sym6]:  78%|███████▊  | 12785/16480 [00:04<00:01, 3309.29curve/s]

Denoising [sym6]:  80%|███████▉  | 13129/16480 [00:04<00:01, 3347.20curve/s]

Denoising [sym6]:  82%|████████▏ | 13464/16480 [00:04<00:00, 3336.75curve/s]

Denoising [sym6]:  84%|████████▎ | 13798/16480 [00:04<00:00, 3163.25curve/s]

Denoising [sym6]:  86%|████████▌ | 14136/16480 [00:04<00:00, 3222.90curve/s]

Denoising [sym6]:  88%|████████▊ | 14461/16480 [00:04<00:00, 3228.88curve/s]

Denoising [sym6]:  90%|████████▉ | 14785/16480 [00:04<00:00, 3228.65curve/s]

Denoising [sym6]:  92%|█████████▏| 15109/16480 [00:04<00:00, 3183.91curve/s]

Denoising [sym6]:  94%|█████████▎| 15429/16480 [00:04<00:00, 3089.05curve/s]

Denoising [sym6]:  96%|█████████▌| 15754/16480 [00:04<00:00, 3134.76curve/s]

Denoising [sym6]:  98%|█████████▊| 16104/16480 [00:05<00:00, 3240.85curve/s]

Denoising [sym6]: 100%|█████████▉| 16429/16480 [00:05<00:00, 3192.10curve/s]

Denoising [sym6]: 100%|██████████| 16480/16480 [00:05<00:00, 3189.65curve/s]

  Wavelet sym6: SNR=13.0dB  TV=0.026  corr=0.9711

  Wavelet sym8: (already in WAVELETS)  SNR=13.3dB

Done. Keys: wv_<name> for each candidate.

In [8]:
# ── Apply SG to all datasets ──────────────────────────────────────
# Override the current chosen window here if needed:
# SG_OPTIMAL_W = 21

print(f'SG    : w={SG_OPTIMAL_W}, p={SG_POLYORDER}')

for folder_name, _ in folders:
    if folder_name not in results: continue
    raw = results[folder_name]['raw']
    print(f'{folder_name}  ({raw.shape[0]} curves) ...', end=' ', flush=True)
    results[folder_name]['sg'] = apply_sg(raw, SG_OPTIMAL_W, SG_POLYORDER)
    print('done.')

print('\nAll methods applied.')

SG    : w=69, p=2
D20260825_E00_C00_F4500KHz_U_DDM_05_01  (17350 curves) ...

done.
D20260825_E00_C00_F4500KHz_U_DDM_06_02  (16971 curves) ...

done.
D20260827_E00_C00_F4500KHz_U_DDM_01_final_final  (16381 curves) ...

done.
D20260827_E00_C00_F4500KHz_U_DDM_02_final_final  (16638 curves) ...

done.
D20260827_E00_C00_F4500KHz_U_DDM_03_final_final  (16754 curves) ...

done.
D20260827_E00_C00_F4500KHz_U_DDM_04_final_final  (16480 curves) ...

done.

All methods applied.

In [9]:
denoising_metrics_by_folder = {}
for folder_name, folder_path in folders:
    denoising_metrics = compare_all_methods(
        folder_name, plot=False,
        methods=['smoothed', 'sg_p2', 'sg_p3', 'sg_p4', 'wv_sym4', 'wv_sym6', 'wv_sym8'])
    denoising_metrics_by_folder[folder_name] = denoising_metrics

### Speed & resource benchmark -- curves/s and peak memory per method

In [10]:
import time
import tracemalloc

BENCH_SAMPLE_SIZE = 400   # matches _derivative_scores' own sample_size convention
BENCH_REPEATS = 3


def _denoise_all_notqdm(curves, wavelet):
    """Same as denoise_all, minus the tqdm progress bar -- its terminal writes would
    unfairly add overhead to the wavelet method's timing vs the vectorized methods."""
    return np.array([denoise_curve(c, wavelet) for c in curves])


def _benchmark_method(fn, curves, n_repeats=BENCH_REPEATS):
    """Mean wall-time throughput (curves/s) and peak traced memory (MB) for a
    denoising call fn(curves) -> denoised, over n_repeats runs."""
    n = len(curves)
    times, peak_mb = [], 0.0
    for _ in range(n_repeats):
        tracemalloc.start()
        t0 = time.perf_counter()
        fn(curves)
        times.append(time.perf_counter() - t0)
        _, peak = tracemalloc.get_traced_memory()
        tracemalloc.stop()
        peak_mb = max(peak_mb, peak / 1e6)
    mean_time = float(np.mean(times))
    return (n / mean_time if mean_time > 0 else np.nan), peak_mb


for folder_name, _ in folders:
    if folder_name not in results or folder_name not in denoising_metrics_by_folder:
        continue
    r      = results[folder_name]
    raw    = r['raw']
    rng    = np.random.default_rng(0)
    sample = raw[rng.choice(len(raw), size=min(BENCH_SAMPLE_SIZE, len(raw)), replace=False)]

    method_fns = {
        f'Smoothed (w={config.WINDOW_SIZE_ORI})':
            lambda c: uniform_filter1d(c, size=config.WINDOW_SIZE_ORI, axis=1, mode='nearest'),
    }
    for poly in SG_POLYORDERS:
        key = f'sg_p{poly}'
        if key in r:
            w = r[key]['optimal_w']
            method_fns[f'SG p={poly} (w={w})'] = lambda c, w=w, p=poly: apply_sg(c, w, p)
    wv_names = dict.fromkeys(list(WAVELETS) + [k[3:] for k in r if k.startswith('wv_')])
    for wv in wv_names:
        method_fns[f'Wavelet ({wv})'] = lambda c, wv=wv: _denoise_all_notqdm(c, wavelet=wv)

    print(f'{folder_name}: benchmarking {len(method_fns)} methods on {len(sample)} curves '
          f'({BENCH_REPEATS} reps each)...')
    speed_col, mem_col = {}, {}
    for label, fn in method_fns.items():
        cps, mem = _benchmark_method(fn, sample)
        speed_col[label] = cps
        mem_col[label]   = mem
        print(f'  {label}: {cps:8.1f} curves/s   {mem:6.2f} MB peak')

    df = denoising_metrics_by_folder[folder_name]
    df['Curves/s']      = pd.Series(speed_col)
    df['Peak Mem (MB)'] = pd.Series(mem_col)

print('\nSpeed/memory benchmark done.')

D20260825_E00_C00_F4500KHz_U_DDM_05_01: benchmarking 7 methods on 400 curves (3 reps each)...
  Smoothed (w=50): 159196.7 curves/s     2.91 MB peak

  SG p=2 (w=113):   5142.5 curves/s     3.70 MB peak

  SG p=3 (w=113):   3190.6 curves/s     3.69 MB peak

  SG p=4 (w=113):   4068.2 curves/s     3.69 MB peak

  Wavelet (sym8):   1177.8 curves/s     5.92 MB peak

  Wavelet (sym4):    984.1 curves/s     5.92 MB peak

  Wavelet (sym6):   1053.4 curves/s     5.92 MB peak
D20260825_E00_C00_F4500KHz_U_DDM_06_02: benchmarking 7 methods on 400 curves (3 reps each)...
  Smoothed (w=50): 179159.3 curves/s     2.93 MB peak
  SG p=2 (w=113):   6299.4 curves/s     3.72 MB peak

  SG p=3 (w=113):   4447.1 curves/s     3.72 MB peak

  SG p=4 (w=113):   3805.8 curves/s     3.72 MB peak

  Wavelet (sym8):   1179.9 curves/s     5.97 MB peak

  Wavelet (sym4):    992.2 curves/s     5.97 MB peak

  Wavelet (sym6):   1090.0 curves/s     5.97 MB peak
D20260827_E00_C00_F4500KHz_U_DDM_01_final_final: benchmarking 7 methods on 400 curves (3 reps each)...
  Smoothed (w=50): 181097.4 curves/s     2.78 MB peak

  SG p=2 (w=109):   5630.0 curves/s     3.55 MB peak

  SG p=3 (w=109):   5083.1 curves/s     3.55 MB peak

  SG p=4 (w=109):   3422.8 curves/s     3.54 MB peak

  Wavelet (sym8):   1182.0 curves/s     5.67 MB peak

  Wavelet (sym4):   1140.4 curves/s     5.67 MB peak

  Wavelet (sym6):   1123.8 curves/s     5.67 MB peak
D20260827_E00_C00_F4500KHz_U_DDM_02_final_final: benchmarking 7 methods on 400 curves (3 reps each)...
  Smoothed (w=50): 184284.8 curves/s     2.90 MB peak

  SG p=2 (w=113):   5777.1 curves/s     3.69 MB peak

  SG p=3 (w=113):   3276.4 curves/s     3.69 MB peak

  SG p=4 (w=113):   3488.1 curves/s     3.68 MB peak

  Wavelet (sym8):   1202.0 curves/s     5.90 MB peak

  Wavelet (sym4):   1008.9 curves/s     5.90 MB peak

  Wavelet (sym6):   1177.6 curves/s     5.90 MB peak
D20260827_E00_C00_F4500KHz_U_DDM_03_final_final: benchmarking 7 methods on 400 curves (3 reps each)...
  Smoothed (w=50): 296525.5 curves/s     1.79 MB peak
  SG p=2 (w=71):   7293.3 curves/s     2.46 MB peak

  SG p=3 (w=71):   5798.2 curves/s     2.46 MB peak
  SG p=4 (w=71):   7153.8 curves/s     2.45 MB peak

  Wavelet (sym8):   1201.6 curves/s     3.69 MB peak

  Wavelet (sym4):   1132.1 curves/s     3.69 MB peak

  Wavelet (sym6):   1255.5 curves/s     3.69 MB peak
D20260827_E00_C00_F4500KHz_U_DDM_04_final_final: benchmarking 7 methods on 400 curves (3 reps each)...
  Smoothed (w=50): 182563.2 curves/s     2.78 MB peak
  SG p=2 (w=109):   7760.0 curves/s     3.54 MB peak

  SG p=3 (w=109):   5899.7 curves/s     3.54 MB peak

  SG p=4 (w=109):   4526.8 curves/s     3.54 MB peak

  Wavelet (sym8):   1215.4 curves/s     5.66 MB peak

  Wavelet (sym4):   1152.7 curves/s     5.66 MB peak

  Wavelet (sym6):   1081.6 curves/s     5.66 MB peak

Speed/memory benchmark done.

### Averaged metrics across all chips

All 7 metrics from `compare_all_methods`, averaged across every chip. SG rows are grouped
by polyorder only (`SG p=2`/`p=3`/`p=4`) -- the per-chip auto-tuned window is stripped
before averaging (`_method_family_key`) since it differs across chips; the displayed window
is the mean of each chip's own value, marked `w=~..`.

In [11]:
avg_denoising_metrics = _average_metrics_df(denoising_metrics_by_folder, folders, show_window=False)
print(f"Averaged across {len(folders)} chips:")
try:
    from IPython.display import display
    display(avg_denoising_metrics.style.apply(_highlight_best).format('{:.4f}', na_rep='N/A'))
except Exception:
    print(avg_denoising_metrics.round(4).to_string())

Averaged across 6 chips:

### LaTeX table -- Residual AC lag-1 / SNR (dB) / Fidelity (corr) per chip

One sub-table per chip (`DDM_0x` -> `Chip 0x`), restricted to the three metrics
above. Methods are grouped as `Smoothed: Simple Moving Average` / `SG:
Savitzky-Golay` / `Wavelet: DWT`, with the per-row hyperparameter
(`w=`/`p=.. w=..`/`sym..`) split into its own column.

In [12]:
import re
import string

def _chip_label(folder_name):
    m = re.search(r'DDM_(\d+)', folder_name)
    return f'Chip {int(m.group(1)):02d}' if m else folder_name


def _split_method_label(label):
    """'Smoothed (w=15)' -> ('Smoothed: Simple Moving Average', '(w=15)')
       'SG p=2 (w=31)'   -> ('SG: Savitzky-Golay', '(p=2 w=31)')
       'SG p=2 (w=~29)'  -> ('SG: Savitzky-Golay', '(p=2 w=~29)')  -- averaged-panel window
       'Wavelet (sym4)'  -> ('Wavelet: DWT', '(sym4)')"""
    m = re.match(r'^SG p=(\d+) \(w=(~?\d+)\)$', label)
    if m:
        return 'SG: Savitzky-Golay', f'(p={m.group(1)} w={m.group(2)})'
    m = re.match(r'^Smoothed \((w=\d+)\)$', label)
    if m:
        return 'Smoothed: Simple Moving Average', f'({m.group(1)})'
    m = re.match(r'^Wavelet \((.+)\)$', label)
    if m:
        return 'Wavelet: DWT', f'({m.group(1)})'
    return label, ''


_LATEX_METRIC_COLS      = ['Residual AC lag-1', 'SNR (dB)', 'Fidelity (corr)', 'Curves/s', 'Peak Mem (MB)']
_LATEX_METRIC_HEADERS   = ['Residual Autocorrelation (Lag-1)', 'SNR (dB)', 'Fidelity (Corr)', 'Curves/s', 'Peak Mem (MB)']
_LATEX_METRIC_FMT       = ['{:.3f}', '{:.2f}', '{:.3f}', '{:.0f}', '{:.2f}']
_LATEX_METRIC_DIRECTION = ['min', 'max', 'max', 'max', 'min']  # residual AC: lower is better; SNR/fidelity/speed: higher; memory: lower


def _latex_panel(df, panel_letter, chip_name, std_df=None):
    best_row = {
        col: (df[col].idxmin() if direction == 'min' else df[col].idxmax())
        for col, direction in zip(_LATEX_METRIC_COLS, _LATEX_METRIC_DIRECTION)
    }

    lines = [
        f'    ({panel_letter}) Performance on {chip_name}\\\\[0.5em]',
        '    \\resizebox{\\textwidth}{!}{',
        '    \\begin{tabular}{llrrr}',
        '    \\toprule',
        '    \\textbf{Method} & \\textbf{Hyperparameter} & \\textbf{'
        + '} & \\textbf{'.join(_LATEX_METRIC_HEADERS) + '} \\\\',
        '    \\midrule',
    ]
    for method_label, row in df.iterrows():
        method_name, hp = _split_method_label(method_label)
        cells = []
        for col, fmt in zip(_LATEX_METRIC_COLS, _LATEX_METRIC_FMT):
            cell = fmt.format(row[col])
            if std_df is not None and method_label in std_df.index and pd.notna(std_df.loc[method_label, col]):
                cell = f'{cell} $\\pm$ {fmt.format(std_df.loc[method_label, col])}'
            if method_label == best_row[col]:
                cell = f'\\textbf{{{cell}}}'
            cells.append(cell)
        lines.append(f'    {method_name} & {hp} & {" & ".join(cells)} \\\\')
    lines += ['    \\bottomrule', '    \\end{tabular}', '    }']
    return '\n'.join(lines)


def build_denoising_latex_table(metrics_by_folder, folders, caption, label, include_average=True):
    used_folders = [f for f in folders if f[0] in metrics_by_folder]
    panels = [
        _latex_panel(metrics_by_folder[folder_name], string.ascii_lowercase[i], _chip_label(folder_name))
        for i, (folder_name, _) in enumerate(used_folders)
    ]
    if include_average and used_folders:
        avg_df, std_df = _average_metrics_df(metrics_by_folder, used_folders,
                                              metric_cols=_LATEX_METRIC_COLS, return_std=True)
        panels.append(_latex_panel(avg_df, string.ascii_lowercase[len(used_folders)],
                                   f'Mean of All {len(used_folders)} Chips', std_df=std_df))
    body = '\n\n    \\vspace{2.5em}\n\n'.join(panels)
    return (
        '\\begin{table}[htbp]\n'
        '    \\centering\n'
        f'    \\caption{{{caption}}}\n'
        f'    \\label{{{label}}}\n'
        '    \\small\n\n'
        f'{body}\n'
        '\\end{table}'
    )


denoising_latex = build_denoising_latex_table(
    denoising_metrics_by_folder, folders,
    caption='Denoising method comparison across the evaluated chips.',
    label='tab:denoising_comparison',
)
print(denoising_latex)

\begin{table}[htbp]
    \centering
    \caption{Denoising method comparison across the evaluated chips.}
    \label{tab:denoising_comparison}
    \small

    (a) Performance on Chip 05\\[0.5em]
    \resizebox{\textwidth}{!}{
    \begin{tabular}{llrrr}
    \toprule
    \textbf{Method} & \textbf{Hyperparameter} & \textbf{Residual Autocorrelation (Lag-1)} & \textbf{SNR (dB)} & \textbf{Fidelity (Corr)} & \textbf{Curves/s} & \textbf{Peak Mem (MB)} \\
    \midrule
    Smoothed: Simple Moving Average & (w=50) & 0.194 & 13.90 & 0.974 & \textbf{159197} & \textbf{2.91} \\
    SG: Savitzky-Golay & (p=2 w=113) & 0.201 & 13.88 & 0.974 & 5142 & 3.70 \\
    SG: Savitzky-Golay & (p=3 w=113) & 0.196 & 13.90 & 0.974 & 3191 & 3.69 \\
    SG: Savitzky-Golay & (p=4 w=113) & 0.148 & 14.18 & 0.976 & 4068 & 3.69 \\
    Wavelet: DWT & (sym4) & 0.237 & 13.67 & 0.973 & 984 & 5.92 \\
    Wavelet: DWT & (sym6) & 0.197 & 13.93 & 0.974 & 1053 & 5.92 \\
    Wavelet: DWT & (sym8) & \textbf{0.142} & \textbf{14.23} & \textbf{0.976} & 1178 & 5.92 \\
    \bottomrule
    \end{tabular}
    }

    \vspace{2.5em}

    (b) Performance on Chip 06\\[0.5em]
    \resizebox{\textwidth}{!}{
    \begin{tabular}{llrrr}
    \toprule
    \textbf{Method} & \textbf{Hyperparameter} & \textbf{Residual Autocorrelation (Lag-1)} & \textbf{SNR (dB)} & \textbf{Fidelity (Corr)} & \textbf{Curves/s} & \textbf{Peak Mem (MB)} \\
    \midrule
    Smoothed: Simple Moving Average & (w=50) & 0.174 & 10.87 & 0.940 & \textbf{179159} & \textbf{2.93} \\
    SG: Savitzky-Golay & (p=2 w=113) & 0.179 & 10.88 & 0.939 & 6299 & 3.72 \\
    SG: Savitzky-Golay & (p=3 w=113) & 0.175 & 10.92 & 0.940 & 4447 & 3.72 \\
    SG: Savitzky-Golay & (p=4 w=113) & 0.130 & 11.20 & 0.943 & 3806 & 3.72 \\
    Wavelet: DWT & (sym4) & 0.221 & 10.62 & 0.936 & 992 & 5.97 \\
    Wavelet: DWT & (sym6) & 0.180 & 10.91 & 0.940 & 1090 & 5.97 \\
    Wavelet: DWT & (sym8) & \textbf{0.122} & \textbf{11.27} & \textbf{0.944} & 1180 & 5.97 \\
    \bottomrule
    \end{tabular}
    }

    \vspace{2.5em}

    (c) Performance on Chip 01\\[0.5em]
    \resizebox{\textwidth}{!}{
    \begin{tabular}{llrrr}
    \toprule
    \textbf{Method} & \textbf{Hyperparameter} & \textbf{Residual Autocorrelation (Lag-1)} & \textbf{SNR (dB)} & \textbf{Fidelity (Corr)} & \textbf{Curves/s} & \textbf{Peak Mem (MB)} \\
    \midrule
    Smoothed: Simple Moving Average & (w=50) & 0.182 & 14.99 & 0.981 & \textbf{181097} & \textbf{2.78} \\
    SG: Savitzky-Golay & (p=2 w=109) & 0.184 & 15.00 & 0.981 & 5630 & 3.55 \\
    SG: Savitzky-Golay & (p=3 w=109) & 0.177 & 15.03 & 0.981 & 5083 & 3.55 \\
    SG: Savitzky-Golay & (p=4 w=109) & 0.135 & 15.27 & 0.982 & 3423 & 3.54 \\
    Wavelet: DWT & (sym4) & 0.187 & 15.02 & 0.981 & 1140 & 5.67 \\
    Wavelet: DWT & (sym6) & 0.185 & 15.03 & 0.981 & 1124 & 5.67 \\
    Wavelet: DWT & (sym8) & \textbf{0.130} & \textbf{15.32} & \textbf{0.982} & 1182 & 5.67 \\
    \bottomrule
    \end{tabular}
    }

    \vspace{2.5em}

    (d) Performance on Chip 02\\[0.5em]
    \resizebox{\textwidth}{!}{
    \begin{tabular}{llrrr}
    \toprule
    \textbf{Method} & \textbf{Hyperparameter} & \textbf{Residual Autocorrelation (Lag-1)} & \textbf{SNR (dB)} & \textbf{Fidelity (Corr)} & \textbf{Curves/s} & \textbf{Peak Mem (MB)} \\
    \midrule
    Smoothed: Simple Moving Average & (w=50) & 0.196 & 16.71 & 0.985 & \textbf{184285} & \textbf{2.90} \\
    SG: Savitzky-Golay & (p=2 w=113) & 0.197 & 16.71 & 0.984 & 5777 & 3.69 \\
    SG: Savitzky-Golay & (p=3 w=113) & 0.188 & 16.75 & 0.985 & 3276 & 3.69 \\
    SG: Savitzky-Golay & (p=4 w=113) & 0.149 & 16.97 & 0.985 & 3488 & 3.68 \\
    Wavelet: DWT & (sym4) & 0.239 & 16.49 & 0.984 & 1009 & 5.90 \\
    Wavelet: DWT & (sym6) & 0.196 & 16.75 & 0.985 & 1178 & 5.90 \\
    Wavelet: DWT & (sym8) & \textbf{0.139} & \textbf{17.05} & \textbf{0.986} & 1202 & 5.90 \\
    \bottomrule
    \end{tabular}
    }

    \vspace{2.5em}

    (e) Performance on Chip 03\\[0.5em]
    \resizebox{\textwidth}{!}{
    \begin{tabular}{llrrr}
    \toprule
    \textbf{Method} & \textbf{Hyperparameter} & \textbf{Residual Autocorrelation (Lag-1)} & \textbf{SNR (dB)} & \textbf{Fidelity (Corr)} & \textbf{Curves/s} & \textbf{Peak Mem (MB)} \\
    \midrule
    Smoothed: Simple Moving Average & (w=50) & 0.169 & 12.43 & 0.954 & \textbf{296526} & \textbf{1.79} \\
    SG: Savitzky-Golay & (p=2 w=71) & 0.114 & 12.77 & 0.957 & 7293 & 2.46 \\
    SG: Savitzky-Golay & (p=3 w=71) & 0.108 & 12.79 & 0.957 & 5798 & 2.46 \\
    SG: Savitzky-Golay & (p=4 w=71) & \textbf{0.056} & \textbf{13.09} & \textbf{0.960} & 7154 & 2.45 \\
    Wavelet: DWT & (sym4) & 0.172 & 12.45 & 0.954 & 1132 & 3.69 \\
    Wavelet: DWT & (sym6) & 0.109 & 12.84 & 0.957 & 1255 & 3.69 \\
    Wavelet: DWT & (sym8) & 0.108 & 12.84 & 0.957 & 1202 & 3.69 \\
    \bottomrule
    \end{tabular}
    }

    \vspace{2.5em}

    (f) Performance on Chip 04\\[0.5em]
    \resizebox{\textwidth}{!}{
    \begin{tabular}{llrrr}
    \toprule
    \textbf{Method} & \textbf{Hyperparameter} & \textbf{Residual Autocorrelation (Lag-1)} & \textbf{SNR (dB)} & \textbf{Fidelity (Corr)} & \textbf{Curves/s} & \textbf{Peak Mem (MB)} \\
    \midrule
    Smoothed: Simple Moving Average & (w=50) & 0.205 & 12.96 & 0.971 & \textbf{182563} & \textbf{2.78} \\
    SG: Savitzky-Golay & (p=2 w=109) & 0.207 & 12.99 & 0.971 & 7760 & 3.54 \\
    SG: Savitzky-Golay & (p=3 w=109) & 0.200 & 13.02 & 0.971 & 5900 & 3.54 \\
    SG: Savitzky-Golay & (p=4 w=109) & 0.159 & 13.27 & 0.973 & 4527 & 3.54 \\
    Wavelet: DWT & (sym4) & 0.208 & 13.01 & 0.971 & 1153 & 5.66 \\
    Wavelet: DWT & (sym6) & 0.206 & 13.02 & 0.971 & 1082 & 5.66 \\
    Wavelet: DWT & (sym8) & \textbf{0.154} & \textbf{13.32} & \textbf{0.973} & 1215 & 5.66 \\
    \bottomrule
    \end{tabular}
    }

    \vspace{2.5em}

    (g) Performance on Mean of All 6 Chips\\[0.5em]
    \resizebox{\textwidth}{!}{
    \begin{tabular}{llrrr}
    \toprule
    \textbf{Method} & \textbf{Hyperparameter} & \textbf{Residual Autocorrelation (Lag-1)} & \textbf{SNR (dB)} & \textbf{Fidelity (Corr)} & \textbf{Curves/s} & \textbf{Peak Mem (MB)} \\
    \midrule
    Smoothed: Simple Moving Average & (w=50) & 0.186 $\pm$ 0.014 & 13.64 $\pm$ 2.04 & 0.967 $\pm$ 0.017 & \textbf{197138 $\pm$ 49549} & \textbf{2.68 $\pm$ 0.44} \\
    SG: Savitzky-Golay & (p=2 w=~105) & 0.180 $\pm$ 0.034 & 13.70 $\pm$ 2.00 & 0.968 $\pm$ 0.017 & 6317 $\pm$ 1018 & 3.44 $\pm$ 0.49 \\
    SG: Savitzky-Golay & (p=3 w=~105) & 0.174 $\pm$ 0.034 & 13.73 $\pm$ 2.01 & 0.968 $\pm$ 0.017 & 4616 $\pm$ 1193 & 3.44 $\pm$ 0.49 \\
    SG: Savitzky-Golay & (p=4 w=~105) & \textbf{0.129 $\pm$ 0.038} & 14.00 $\pm$ 1.99 & \textbf{0.970 $\pm$ 0.016} & 4411 $\pm$ 1403 & 3.44 $\pm$ 0.49 \\
    Wavelet: DWT & (sym4) & 0.211 $\pm$ 0.027 & 13.54 $\pm$ 2.04 & 0.967 $\pm$ 0.018 & 1068 $\pm$ 81 & 5.47 $\pm$ 0.88 \\
    Wavelet: DWT & (sym6) & 0.179 $\pm$ 0.035 & 13.75 $\pm$ 2.00 & 0.968 $\pm$ 0.017 & 1130 $\pm$ 75 & 5.47 $\pm$ 0.88 \\
    Wavelet: DWT & (sym8) & 0.133 $\pm$ 0.016 & \textbf{14.01 $\pm$ 2.02} & 0.970 $\pm$ 0.016 & 1193 $\pm$ 15 & 5.47 $\pm$ 0.88 \\
    \bottomrule
    \end{tabular}
    }
\end{table}

### LaTeX summary table -- single flat table, mean $\pm$ std across chips (bold = best)

In [13]:
def _summary_method_hp(label):
    """Like _split_method_label, but drops the short-form prefix ('SG: ' etc.) and
    SG's auto-tuned window (a single number isn't meaningful once averaged across
    chips, where each chip found its own optimal_w) -- matches this flat summary
    table's simpler (method name, hyperparameter) style, e.g. 'Savitzky-Golay' / '(p=2)'."""
    name, hp = _split_method_label(label)
    # 'Smoothed: Simple Moving Average' / 'SG: Savitzky-Golay' -> keep the part after
    # the colon (the long-form name); 'Wavelet: DWT' -> keep 'Wavelet' instead, since
    # that's the family name the reference table actually uses, not the transform name.
    name = 'Wavelet' if name.startswith('Wavelet:') else name.split(': ', 1)[-1]
    m = re.match(r'^\(p=(\d+) w=~?\d+\)$', hp)
    if m:
        hp = f'(p={m.group(1)})'
    return name, hp


# (metric name, unit, LaTeX arrow) -- stacked 2-line header matching the reference style.
_SUMMARY_METRIC_HEADERS = [
    ('Residual Autocorrelation', '(Lag-1)',    '\\downarrow'),
    ('SNR',                      '(dB)',       '\\uparrow'),
    ('Fidelity',                 '(Corr)',     '\\uparrow'),
    ('Speed',                    '(curves/s)', '\\uparrow'),
    ('Peak Memory',              '(MB)',       '\\downarrow'),
]


def build_denoising_summary_latex_table(metrics_by_folder, folders, caption, label,
                                        metric_cols=_LATEX_METRIC_COLS,
                                        metric_headers=_SUMMARY_METRIC_HEADERS,
                                        metric_fmt=_LATEX_METRIC_FMT,
                                        metric_direction=_LATEX_METRIC_DIRECTION):
    """Single flat table (methods as rows, metrics as columns, mean $\pm$ std across
    chips) -- unlike build_denoising_latex_table's per-chip + average panels, this is
    just the one summary panel, styled to match the target LaTeX reference exactly
    (stacked 2-line headers with a bold direction arrow, resizebox, bold-best)."""
    # show_window=True: keep the (w=~XX) suffix on SG labels so _split_method_label's
    # regex (and _summary_method_hp's window-stripping below) can actually match it --
    # show_window=False would drop it upstream, leaving nothing for either to parse.
    avg_df, std_df = _average_metrics_df(metrics_by_folder, folders, metric_cols=metric_cols,
                                         show_window=True, return_std=True)
    best_row = {
        col: (avg_df[col].idxmin() if d == 'min' else avg_df[col].idxmax())
        for col, d in zip(metric_cols, metric_direction)
    }

    header_cells = [
        f'\\begin{{tabular}}[b]{{@{{}}r@{{}}}}\\textbf{{{name}}}\\\\ '
        f'\\textbf{{{unit}}} $\\boldsymbol{{{arrow}}}$\\end{{tabular}}'
        for name, unit, arrow in metric_headers
    ]

    lines = [
        '\\begin{table}[htbp]',
        '    \\centering',
        f'    \\caption{{{caption}}}',
        f'    \\label{{{label}}}',
        '    \\small',
        '    \\resizebox{\\textwidth}{!}{',
        '    \\begin{tabular}{ll' + 'r' * len(metric_cols) + '}',
        '    \\toprule',
        '    \\textbf{Method} & \\textbf{Hyperparameter} & \n    '
        + ' & \n    '.join(header_cells) + ' \\\\',
        '    \\midrule',
    ]
    for method_label, row in avg_df.iterrows():
        name, hp = _summary_method_hp(method_label)
        cells_out = []
        for col, fmt in zip(metric_cols, metric_fmt):
            val  = fmt.format(row[col])
            sd   = std_df.loc[method_label, col] if method_label in std_df.index else np.nan
            cell = f'{val} $\\pm$ {fmt.format(sd)}' if pd.notna(sd) else val
            if method_label == best_row[col]:
                cell = f'\\textbf{{{cell}}}'
            cells_out.append(cell)
        lines.append(f'    {name} & {hp} & {" & ".join(cells_out)} \\\\')
    lines += ['    \\bottomrule', '    \\end{tabular}', '    }', '\\end{table}']
    return '\n'.join(lines)


denoising_summary_latex = build_denoising_summary_latex_table(
    denoising_metrics_by_folder, folders,
    caption='Quantitative comparison of denoising methods evaluated across all eLAMP chips. Bold marks the best result.',
    label='tab:denoising_comparison',
)
print(denoising_summary_latex)

\begin{table}[htbp]
    \centering
    \caption{Quantitative comparison of denoising methods evaluated across all eLAMP chips. Bold marks the best result.}
    \label{tab:denoising_comparison}
    \small
    \resizebox{\textwidth}{!}{
    \begin{tabular}{llrrrrr}
    \toprule
    \textbf{Method} & \textbf{Hyperparameter} &
    \begin{tabular}[b]{@{}r@{}}\textbf{Residual Autocorrelation}\\ \textbf{(Lag-1)} $\boldsymbol{\downarrow}$\end{tabular} &
    \begin{tabular}[b]{@{}r@{}}\textbf{SNR}\\ \textbf{(dB)} $\boldsymbol{\uparrow}$\end{tabular} &
    \begin{tabular}[b]{@{}r@{}}\textbf{Fidelity}\\ \textbf{(Corr)} $\boldsymbol{\uparrow}$\end{tabular} &
    \begin{tabular}[b]{@{}r@{}}\textbf{Speed}\\ \textbf{(curves/s)} $\boldsymbol{\uparrow}$\end{tabular} &
    \begin{tabular}[b]{@{}r@{}}\textbf{Peak Memory}\\ \textbf{(MB)} $\boldsymbol{\downarrow}$\end{tabular} \\
    \midrule
    Simple Moving Average & (w=50) & 0.186 $\pm$ 0.014 & 13.64 $\pm$ 2.04 & 0.967 $\pm$ 0.017 & \textbf{197138 $\pm$ 49549} & \textbf{2.68 $\pm$ 0.44} \\
    Savitzky-Golay & (p=2) & 0.180 $\pm$ 0.034 & 13.70 $\pm$ 2.00 & 0.968 $\pm$ 0.017 & 6317 $\pm$ 1018 & 3.44 $\pm$ 0.49 \\
    Savitzky-Golay & (p=3) & 0.174 $\pm$ 0.034 & 13.73 $\pm$ 2.01 & 0.968 $\pm$ 0.017 & 4616 $\pm$ 1193 & 3.44 $\pm$ 0.49 \\
    Savitzky-Golay & (p=4) & \textbf{0.129 $\pm$ 0.038} & 14.00 $\pm$ 1.99 & \textbf{0.970 $\pm$ 0.016} & 4411 $\pm$ 1403 & 3.44 $\pm$ 0.49 \\
    Wavelet & (sym4) & 0.211 $\pm$ 0.027 & 13.54 $\pm$ 2.04 & 0.967 $\pm$ 0.018 & 1068 $\pm$ 81 & 5.47 $\pm$ 0.88 \\
    Wavelet & (sym6) & 0.179 $\pm$ 0.035 & 13.75 $\pm$ 2.00 & 0.968 $\pm$ 0.017 & 1130 $\pm$ 75 & 5.47 $\pm$ 0.88 \\
    Wavelet & (sym8) & 0.133 $\pm$ 0.016 & \textbf{14.01 $\pm$ 2.02} & 0.970 $\pm$ 0.016 & 1193 $\pm$ 15 & 5.47 $\pm$ 0.88 \\
    \bottomrule
    \end{tabular}
    }
\end{table}

<>:32: SyntaxWarning: invalid escape sequence '\p'
<>:32: SyntaxWarning: invalid escape sequence '\p'
/tmp/ipykernel_1020536/2890353397.py:32: SyntaxWarning: invalid escape sequence '\p'
  """Single flat table (methods as rows, metrics as columns, mean $\pm$ std across

In [14]:
mnames = ['Residual AC lag-1', 'SNR (dB)', 'Fidelity (corr)']
mascs = [True, False, False]
top_n = 5
for mname, masc in zip(mnames, mascs):
    print(f'\nTop {top_n} methods by {mname}:')
    display(denoising_metrics.sort_values(by=mname, ascending=masc)[[mname]].head(top_n))

Top 5 methods by Residual AC lag-1:

                 Residual AC lag-1
Wavelet (sym8)            0.154239
SG p=4 (w=109)            0.158827
SG p=3 (w=109)            0.200005
Smoothed (w=50)           0.204742
Wavelet (sym6)            0.206066

Top 5 methods by SNR (dB):

                 SNR (dB)
Wavelet (sym8)  13.317272
SG p=4 (w=109)  13.266785
Wavelet (sym6)  13.020261
SG p=3 (w=109)  13.015920
Wavelet (sym4)  13.005883

Top 5 methods by Fidelity (corr):

                Fidelity (corr)
Wavelet (sym8)         0.972904
SG p=4 (w=109)         0.972616
SG p=3 (w=109)         0.971169
Wavelet (sym6)         0.971146
Wavelet (sym4)         0.971078